EXEC [dbo].pts_CheckProc 'pts_Product_Update'
 GO

CREATE PROCEDURE [dbo].pts_Product_Update ( 
   @ProductID int,
   @CompanyID int,
   @ProductTypeID int,
   @ProductName nvarchar (40),
   @Image nvarchar (40),
   @Price money,
   @OriginalPrice money,
   @IsTaxable bit,
   @TaxRate money,
   @Tax money,
   @Description nvarchar (2000),
   @Seq int,
   @IsActive bit,
   @IsPrivate bit,
   @IsPublic bit,
   @NoQty bit,
   @Data nvarchar (80),
   @Email nvarchar (80),
   @InputOptions nvarchar (2000),
   @Ship1 money,
   @Ship2 money,
   @Ship3 money,
   @Ship4 money,
   @Ship1a money,
   @Ship2a money,
   @Ship3a money,
   @Ship4a money,
   @Fulfill int,
   @Recur int,
   @RecurTerm varchar (10),
   @CommPlan int,
   @BV money,
   @QV money,
   @Code varchar (10),
   @Inventory int,
   @InStock int,
   @ReOrder int,
   @IsShip bit,
   @OrderMin int,
   @OrderMax int,
   @OrderMul int,
   @OrderGrp varchar (10),
   @Attribute1 varchar (15),
   @Attribute2 varchar (15),
   @Attribute3 varchar (15),
   @Levels varchar (5),
   @FulFillInfo varchar (100),
   @UserID int
      )
AS

DECLARE @mNow datetime

SET NOCOUNT ON

SET @mNow = GETDATE()

UPDATE pd
SET pd.CompanyID = @CompanyID ,
   pd.ProductTypeID = @ProductTypeID ,
   pd.ProductName = @ProductName ,
   pd.Image = @Image ,
   pd.Price = @Price ,
   pd.OriginalPrice = @OriginalPrice ,
   pd.IsTaxable = @IsTaxable ,
   pd.TaxRate = @TaxRate ,
   pd.Tax = @Tax ,
   pd.Description = @Description ,
   pd.Seq = @Seq ,
   pd.IsActive = @IsActive ,
   pd.IsPrivate = @IsPrivate ,
   pd.IsPublic = @IsPublic ,
   pd.NoQty = @NoQty ,
   pd.Data = @Data ,
   pd.Email = @Email ,
   pd.InputOptions = @InputOptions ,
   pd.Ship1 = @Ship1 ,
   pd.Ship2 = @Ship2 ,
   pd.Ship3 = @Ship3 ,
   pd.Ship4 = @Ship4 ,
   pd.Ship1a = @Ship1a ,
   pd.Ship2a = @Ship2a ,
   pd.Ship3a = @Ship3a ,
   pd.Ship4a = @Ship4a ,
   pd.Fulfill = @Fulfill ,
   pd.Recur = @Recur ,
   pd.RecurTerm = @RecurTerm ,
   pd.CommPlan = @CommPlan ,
   pd.BV = @BV ,
   pd.QV = @QV ,
   pd.Code = @Code ,
   pd.Inventory = @Inventory ,
   pd.InStock = @InStock ,
   pd.ReOrder = @ReOrder ,
   pd.IsShip = @IsShip ,
   pd.OrderMin = @OrderMin ,
   pd.OrderMax = @OrderMax ,
   pd.OrderMul = @OrderMul ,
   pd.OrderGrp = @OrderGrp ,
   pd.Attribute1 = @Attribute1 ,
   pd.Attribute2 = @Attribute2 ,
   pd.Attribute3 = @Attribute3 ,
   pd.Levels = @Levels ,
   pd.FulFillInfo = @FulFillInfo
FROM Product AS pd
WHERE pd.ProductID = @ProductID

GO