EXEC [dbo].pts_CheckProc 'pts_BarterAd_Add'
 GO

CREATE PROCEDURE [dbo].pts_BarterAd_Add ( 
   @BarterAdID int OUTPUT,
   @ConsumerID int,
   @BarterArea1ID int,
   @BarterArea2ID int,
   @BarterCategoryID int,
   @Title nvarchar (100),
   @Status int,
   @PostDate datetime,
   @UpdateDate datetime,
   @EndDate datetime,
   @Price money,
   @Location nvarchar (40),
   @Zip nvarchar (10),
   @Description nvarchar (4000),
   @Language nvarchar (10),
   @ContactName nvarchar (40),
   @ContactEmail nvarchar (80),
   @ContactPhone nvarchar (40),
   @IsEmail bit,
   @IsPhone bit,
   @IsText bit,
   @IsMore bit,
   @IsMap bit,
   @IsContact bit,
   @IsDealer bit,
   @MapStreet1 nvarchar (60),
   @MapStreet2 nvarchar (60),
   @MapCity nvarchar (30),
   @MapZip nvarchar (10),
   @Options varchar (20),
   @Payments varchar (20),
   @Condition int,
   @Images int,
   @GeoCode varchar (30),
   @T1 nvarchar (40),
   @T2 nvarchar (40),
   @T3 nvarchar (40),
   @T4 nvarchar (40),
   @T5 nvarchar (40),
   @N1 int,
   @N2 int,
   @N3 int,
   @N4 int,
   @N5 int,
   @L1 tinyint,
   @L2 tinyint,
   @L3 tinyint,
   @L4 tinyint,
   @L5 tinyint,
   @L6 tinyint,
   @L7 tinyint,
   @L8 tinyint,
   @L9 tinyint,
   @L10 tinyint,
   @Y1 bit,
   @Y2 bit,
   @Y3 bit,
   @Y4 bit,
   @Y5 bit,
   @Y6 bit,
   @Y7 bit,
   @Y8 bit,
   @Y9 bit,
   @Y10 bit,
   @D1 datetime,
   @D2 datetime,
   @D3 datetime,
   @D4 datetime,
   @D5 datetime,
   @UserID int
      )
AS

DECLARE @mNow datetime
DECLARE @mNewID int

SET NOCOUNT ON

SET @mNow = GETDATE()


INSERT INTO BarterAd (
            ConsumerID , 
            BarterArea1ID , 
            BarterArea2ID , 
            BarterCategoryID , 
            Title , 
            Status , 
            PostDate , 
            UpdateDate , 
            EndDate , 
            Price , 
            Location , 
            Zip , 
            Description , 
            Language , 
            ContactName , 
            ContactEmail , 
            ContactPhone , 
            IsEmail , 
            IsPhone , 
            IsText , 
            IsMore , 
            IsMap , 
            IsContact , 
            IsDealer , 
            MapStreet1 , 
            MapStreet2 , 
            MapCity , 
            MapZip , 
            Options , 
            Payments , 
            Condition , 
            Images , 
            GeoCode , 
            T1 , 
            T2 , 
            T3 , 
            T4 , 
            T5 , 
            N1 , 
            N2 , 
            N3 , 
            N4 , 
            N5 , 
            L1 , 
            L2 , 
            L3 , 
            L4 , 
            L5 , 
            L6 , 
            L7 , 
            L8 , 
            L9 , 
            L10 , 
            Y1 , 
            Y2 , 
            Y3 , 
            Y4 , 
            Y5 , 
            Y6 , 
            Y7 , 
            Y8 , 
            Y9 , 
            Y10 , 
            D1 , 
            D2 , 
            D3 , 
            D4 , 
            D5
            )
VALUES (
            @ConsumerID ,
            @BarterArea1ID ,
            @BarterArea2ID ,
            @BarterCategoryID ,
            @Title ,
            @Status ,
            @PostDate ,
            @UpdateDate ,
            @EndDate ,
            @Price ,
            @Location ,
            @Zip ,
            @Description ,
            @Language ,
            @ContactName ,
            @ContactEmail ,
            @ContactPhone ,
            @IsEmail ,
            @IsPhone ,
            @IsText ,
            @IsMore ,
            @IsMap ,
            @IsContact ,
            @IsDealer ,
            @MapStreet1 ,
            @MapStreet2 ,
            @MapCity ,
            @MapZip ,
            @Options ,
            @Payments ,
            @Condition ,
            @Images ,
            @GeoCode ,
            @T1 ,
            @T2 ,
            @T3 ,
            @T4 ,
            @T5 ,
            @N1 ,
            @N2 ,
            @N3 ,
            @N4 ,
            @N5 ,
            @L1 ,
            @L2 ,
            @L3 ,
            @L4 ,
            @L5 ,
            @L6 ,
            @L7 ,
            @L8 ,
            @L9 ,
            @L10 ,
            @Y1 ,
            @Y2 ,
            @Y3 ,
            @Y4 ,
            @Y5 ,
            @Y6 ,
            @Y7 ,
            @Y8 ,
            @Y9 ,
            @Y10 ,
            @D1 ,
            @D2 ,
            @D3 ,
            @D4 ,
            @D5            )

SET @mNewID = @@IDENTITY

SET @BarterAdID = @mNewID

GO