EXEC [dbo].pts_CheckProc 'pts_Merchant_Add'
 GO

CREATE PROCEDURE [dbo].pts_Merchant_Add ( 
   @MerchantID int OUTPUT,
   @MemberID int,
   @BillingID int,
   @PayoutID int,
   @CountryID int,
   @SweepID int,
   @MerchantName nvarchar (80),
   @NameLast nvarchar (30),
   @NameFirst nvarchar (30),
   @Email nvarchar (80),
   @Email2 nvarchar (80),
   @Email3 nvarchar (80),
   @Phone nvarchar (30),
   @Phone2 nvarchar (30),
   @Password nvarchar (20),
   @Password2 nvarchar (20),
   @Password3 nvarchar (20),
   @Password4 nvarchar (20),
   @Status int,
   @Street1 nvarchar (60),
   @Street2 nvarchar (60),
   @City nvarchar (30),
   @State nvarchar (30),
   @Zip nvarchar (20),
   @Referrals int,
   @Referrals2 int,
   @VisitDate datetime,
   @IsOrg bit,
   @IsAwards bit,
   @EnrollDate datetime,
   @BillDate datetime,
   @BillDays int,
   @Image nvarchar (40),
   @Description nvarchar (2000),
   @Terms nvarchar (100),
   @Options varchar (20),
   @StoreOptions varchar (20),
   @Colors varchar (100),
   @Rating int,
   @CurrencyCode varchar (3),
   @Processor int,
   @Payment varchar (1000),
   @UserKey varchar (40),
   @UserKey3 varchar (40),
   @UserKey4 varchar (40),
   @UserCode varchar (10),
   @Access varchar (80),
   @PromoLimit int,
   @SweepRate int,
   @TimeZone int,
   @GeoCode varchar (30),
   @ReferRate int,
   @UserID int
      )
AS

DECLARE @mNow datetime
DECLARE @mNewID int

SET NOCOUNT ON

SET @mNow = GETDATE()


INSERT INTO Merchant (
            MemberID , 
            BillingID , 
            PayoutID , 
            CountryID , 
            SweepID , 
            MerchantName , 
            NameLast , 
            NameFirst , 
            Email , 
            Email2 , 
            Email3 , 
            Phone , 
            Phone2 , 
            Password , 
            Password2 , 
            Password3 , 
            Password4 , 
            Status , 
            Street1 , 
            Street2 , 
            City , 
            State , 
            Zip , 
            Referrals , 
            Referrals2 , 
            VisitDate , 
            IsOrg , 
            IsAwards , 
            EnrollDate , 
            BillDate , 
            BillDays , 
            Image , 
            Description , 
            Terms , 
            Options , 
            StoreOptions , 
            Colors , 
            Rating , 
            CurrencyCode , 
            Processor , 
            Payment , 
            UserKey , 
            UserKey3 , 
            UserKey4 , 
            UserCode , 
            Access , 
            PromoLimit , 
            SweepRate , 
            TimeZone , 
            GeoCode , 
            ReferRate
            )
VALUES (
            @MemberID ,
            @BillingID ,
            @PayoutID ,
            @CountryID ,
            @SweepID ,
            @MerchantName ,
            @NameLast ,
            @NameFirst ,
            @Email ,
            @Email2 ,
            @Email3 ,
            @Phone ,
            @Phone2 ,
            @Password ,
            @Password2 ,
            @Password3 ,
            @Password4 ,
            @Status ,
            @Street1 ,
            @Street2 ,
            @City ,
            @State ,
            @Zip ,
            @Referrals ,
            @Referrals2 ,
            @VisitDate ,
            @IsOrg ,
            @IsAwards ,
            @EnrollDate ,
            @BillDate ,
            @BillDays ,
            @Image ,
            @Description ,
            @Terms ,
            @Options ,
            @StoreOptions ,
            @Colors ,
            @Rating ,
            @CurrencyCode ,
            @Processor ,
            @Payment ,
            @UserKey ,
            @UserKey3 ,
            @UserKey4 ,
            @UserCode ,
            @Access ,
            @PromoLimit ,
            @SweepRate ,
            @TimeZone ,
            @GeoCode ,
            @ReferRate            )

SET @mNewID = @@IDENTITY

SET @MerchantID = @mNewID

GO