EXEC [dbo].pts_CheckProc 'pts_Profile_Fetch'
 GO

CREATE PROCEDURE [dbo].pts_Profile_Fetch ( 
   @ProfileID int,
   @MemberID int OUTPUT,
   @ProfileDate datetime OUTPUT,
   @ProfileType int OUTPUT,
   @Status int OUTPUT,
   @VQResponse nvarchar (50) OUTPUT,
   @SQResponse nvarchar (50) OUTPUT,
   @VQDiff int OUTPUT,
   @VQDimPerc int OUTPUT,
   @VQDimPos_I int OUTPUT,
   @VQDimPos_E int OUTPUT,
   @VQDimPos_S int OUTPUT,
   @VQDimNeg_I int OUTPUT,
   @VQDimNeg_E int OUTPUT,
   @VQDimNeg_S int OUTPUT,
   @VQIntCate_I int OUTPUT,
   @VQIntCate_E int OUTPUT,
   @VQIntCate_S int OUTPUT,
   @VQInt int OUTPUT,
   @VQIntPerc int OUTPUT,
   @VQDI int OUTPUT,
   @VQDIS int OUTPUT,
   @VQLeft int OUTPUT,
   @VQRight int OUTPUT,
   @VQAI int OUTPUT,
   @SQDiff int OUTPUT,
   @SQDimPerc int OUTPUT,
   @SQDimPos_I int OUTPUT,
   @SQDimPos_E int OUTPUT,
   @SQDimPos_S int OUTPUT,
   @SQDimNeg_I int OUTPUT,
   @SQDimNeg_E int OUTPUT,
   @SQDimNeg_S int OUTPUT,
   @SQIntCate_I int OUTPUT,
   @SQIntCate_E int OUTPUT,
   @SQIntCate_S int OUTPUT,
   @SQInt int OUTPUT,
   @SQIntPerc int OUTPUT,
   @SQDI int OUTPUT,
   @SQDIS int OUTPUT,
   @SQLeft int OUTPUT,
   @SQRight int OUTPUT,
   @SQAI int OUTPUT,
   @BQrLeft money OUTPUT,
   @BQrRight money OUTPUT,
   @BQaLeft int OUTPUT,
   @BQaRight int OUTPUT,
   @CQLeft int OUTPUT,
   @CQRight int OUTPUT,
   @RQLeft money OUTPUT,
   @RQRight money OUTPUT,
   @VQClarity_I int OUTPUT,
   @VQClarity_E int OUTPUT,
   @VQClarity_S int OUTPUT,
   @VQBias_I int OUTPUT,
   @VQBias_E int OUTPUT,
   @VQBias_S int OUTPUT,
   @SQClarity_I int OUTPUT,
   @SQClarity_E int OUTPUT,
   @SQClarity_S int OUTPUT,
   @SQBias_I int OUTPUT,
   @SQBias_E int OUTPUT,
   @SQBias_S int OUTPUT,
   @xVQClarity_I int OUTPUT,
   @xVQClarity_E int OUTPUT,
   @xVQClarity_S int OUTPUT,
   @xVQBias_I money OUTPUT,
   @xVQBias_E money OUTPUT,
   @xVQBias_S money OUTPUT,
   @xSQClarity_I int OUTPUT,
   @xSQClarity_E int OUTPUT,
   @xSQClarity_S int OUTPUT,
   @xSQBias_I money OUTPUT,
   @xSQBias_E money OUTPUT,
   @xSQBias_S money OUTPUT,
   @UserID int
      )
AS


SET NOCOUNT ON


SELECT   @MemberID = pro.MemberID ,
   @ProfileDate = pro.ProfileDate ,
   @ProfileType = pro.ProfileType ,
   @Status = pro.Status ,
   @VQResponse = pro.VQResponse ,
   @SQResponse = pro.SQResponse ,
   @VQDiff = pro.VQDiff ,
   @VQDimPerc = pro.VQDimPerc ,
   @VQDimPos_I = pro.VQDimPos_I ,
   @VQDimPos_E = pro.VQDimPos_E ,
   @VQDimPos_S = pro.VQDimPos_S ,
   @VQDimNeg_I = pro.VQDimNeg_I ,
   @VQDimNeg_E = pro.VQDimNeg_E ,
   @VQDimNeg_S = pro.VQDimNeg_S ,
   @VQIntCate_I = pro.VQIntCate_I ,
   @VQIntCate_E = pro.VQIntCate_E ,
   @VQIntCate_S = pro.VQIntCate_S ,
   @VQInt = pro.VQInt ,
   @VQIntPerc = pro.VQIntPerc ,
   @VQDI = pro.VQDI ,
   @VQDIS = pro.VQDIS ,
   @VQLeft = pro.VQLeft ,
   @VQRight = pro.VQRight ,
   @VQAI = pro.VQAI ,
   @SQDiff = pro.SQDiff ,
   @SQDimPerc = pro.SQDimPerc ,
   @SQDimPos_I = pro.SQDimPos_I ,
   @SQDimPos_E = pro.SQDimPos_E ,
   @SQDimPos_S = pro.SQDimPos_S ,
   @SQDimNeg_I = pro.SQDimNeg_I ,
   @SQDimNeg_E = pro.SQDimNeg_E ,
   @SQDimNeg_S = pro.SQDimNeg_S ,
   @SQIntCate_I = pro.SQIntCate_I ,
   @SQIntCate_E = pro.SQIntCate_E ,
   @SQIntCate_S = pro.SQIntCate_S ,
   @SQInt = pro.SQInt ,
   @SQIntPerc = pro.SQIntPerc ,
   @SQDI = pro.SQDI ,
   @SQDIS = pro.SQDIS ,
   @SQLeft = pro.SQLeft ,
   @SQRight = pro.SQRight ,
   @SQAI = pro.SQAI ,
   @BQrLeft = pro.BQrLeft ,
   @BQrRight = pro.BQrRight ,
   @BQaLeft = pro.BQaLeft ,
   @BQaRight = pro.BQaRight ,
   @CQLeft = pro.CQLeft ,
   @CQRight = pro.CQRight ,
   @RQLeft = pro.RQLeft ,
   @RQRight = pro.RQRight ,
   @VQClarity_I = pro.VQClarity_I ,
   @VQClarity_E = pro.VQClarity_E ,
   @VQClarity_S = pro.VQClarity_S ,
   @VQBias_I = pro.VQBias_I ,
   @VQBias_E = pro.VQBias_E ,
   @VQBias_S = pro.VQBias_S ,
   @SQClarity_I = pro.SQClarity_I ,
   @SQClarity_E = pro.SQClarity_E ,
   @SQClarity_S = pro.SQClarity_S ,
   @SQBias_I = pro.SQBias_I ,
   @SQBias_E = pro.SQBias_E ,
   @SQBias_S = pro.SQBias_S ,
   @xVQClarity_I = pro.xVQClarity_I ,
   @xVQClarity_E = pro.xVQClarity_E ,
   @xVQClarity_S = pro.xVQClarity_S ,
   @xVQBias_I = pro.xVQBias_I ,
   @xVQBias_E = pro.xVQBias_E ,
   @xVQBias_S = pro.xVQBias_S ,
   @xSQClarity_I = pro.xSQClarity_I ,
   @xSQClarity_E = pro.xSQClarity_E ,
   @xSQClarity_S = pro.xSQClarity_S ,
   @xSQBias_I = pro.xSQBias_I ,
   @xSQBias_E = pro.xSQBias_E ,
   @xSQBias_S = pro.xSQBias_S
FROM Profile AS pro (NOLOCK)
WHERE pro.ProfileID = @ProfileID

GO