EXEC [dbo].pts_CheckProc 'pts_Profile_Update'
 GO

CREATE PROCEDURE [dbo].pts_Profile_Update ( 
   @ProfileID int,
   @MemberID int,
   @ProfileDate datetime,
   @ProfileType int,
   @Status int,
   @VQResponse nvarchar (50),
   @SQResponse nvarchar (50),
   @VQDiff int,
   @VQDimPerc int,
   @VQDimPos_I int,
   @VQDimPos_E int,
   @VQDimPos_S int,
   @VQDimNeg_I int,
   @VQDimNeg_E int,
   @VQDimNeg_S int,
   @VQIntCate_I int,
   @VQIntCate_E int,
   @VQIntCate_S int,
   @VQInt int,
   @VQIntPerc int,
   @VQDI int,
   @VQDIS int,
   @VQLeft int,
   @VQRight int,
   @VQAI int,
   @SQDiff int,
   @SQDimPerc int,
   @SQDimPos_I int,
   @SQDimPos_E int,
   @SQDimPos_S int,
   @SQDimNeg_I int,
   @SQDimNeg_E int,
   @SQDimNeg_S int,
   @SQIntCate_I int,
   @SQIntCate_E int,
   @SQIntCate_S int,
   @SQInt int,
   @SQIntPerc int,
   @SQDI int,
   @SQDIS int,
   @SQLeft int,
   @SQRight int,
   @SQAI int,
   @BQrLeft money,
   @BQrRight money,
   @BQaLeft int,
   @BQaRight int,
   @CQLeft int,
   @CQRight int,
   @RQLeft money,
   @RQRight money,
   @VQClarity_I int,
   @VQClarity_E int,
   @VQClarity_S int,
   @VQBias_I int,
   @VQBias_E int,
   @VQBias_S int,
   @SQClarity_I int,
   @SQClarity_E int,
   @SQClarity_S int,
   @SQBias_I int,
   @SQBias_E int,
   @SQBias_S int,
   @xVQClarity_I int,
   @xVQClarity_E int,
   @xVQClarity_S int,
   @xVQBias_I money,
   @xVQBias_E money,
   @xVQBias_S money,
   @xSQClarity_I int,
   @xSQClarity_E int,
   @xSQClarity_S int,
   @xSQBias_I money,
   @xSQBias_E money,
   @xSQBias_S money,
   @UserID int
      )
AS

DECLARE @mNow datetime

SET NOCOUNT ON

SET @mNow = GETDATE()

UPDATE pro
SET pro.MemberID = @MemberID ,
   pro.ProfileDate = @ProfileDate ,
   pro.ProfileType = @ProfileType ,
   pro.Status = @Status ,
   pro.VQResponse = @VQResponse ,
   pro.SQResponse = @SQResponse ,
   pro.VQDiff = @VQDiff ,
   pro.VQDimPerc = @VQDimPerc ,
   pro.VQDimPos_I = @VQDimPos_I ,
   pro.VQDimPos_E = @VQDimPos_E ,
   pro.VQDimPos_S = @VQDimPos_S ,
   pro.VQDimNeg_I = @VQDimNeg_I ,
   pro.VQDimNeg_E = @VQDimNeg_E ,
   pro.VQDimNeg_S = @VQDimNeg_S ,
   pro.VQIntCate_I = @VQIntCate_I ,
   pro.VQIntCate_E = @VQIntCate_E ,
   pro.VQIntCate_S = @VQIntCate_S ,
   pro.VQInt = @VQInt ,
   pro.VQIntPerc = @VQIntPerc ,
   pro.VQDI = @VQDI ,
   pro.VQDIS = @VQDIS ,
   pro.VQLeft = @VQLeft ,
   pro.VQRight = @VQRight ,
   pro.VQAI = @VQAI ,
   pro.SQDiff = @SQDiff ,
   pro.SQDimPerc = @SQDimPerc ,
   pro.SQDimPos_I = @SQDimPos_I ,
   pro.SQDimPos_E = @SQDimPos_E ,
   pro.SQDimPos_S = @SQDimPos_S ,
   pro.SQDimNeg_I = @SQDimNeg_I ,
   pro.SQDimNeg_E = @SQDimNeg_E ,
   pro.SQDimNeg_S = @SQDimNeg_S ,
   pro.SQIntCate_I = @SQIntCate_I ,
   pro.SQIntCate_E = @SQIntCate_E ,
   pro.SQIntCate_S = @SQIntCate_S ,
   pro.SQInt = @SQInt ,
   pro.SQIntPerc = @SQIntPerc ,
   pro.SQDI = @SQDI ,
   pro.SQDIS = @SQDIS ,
   pro.SQLeft = @SQLeft ,
   pro.SQRight = @SQRight ,
   pro.SQAI = @SQAI ,
   pro.BQrLeft = @BQrLeft ,
   pro.BQrRight = @BQrRight ,
   pro.BQaLeft = @BQaLeft ,
   pro.BQaRight = @BQaRight ,
   pro.CQLeft = @CQLeft ,
   pro.CQRight = @CQRight ,
   pro.RQLeft = @RQLeft ,
   pro.RQRight = @RQRight ,
   pro.VQClarity_I = @VQClarity_I ,
   pro.VQClarity_E = @VQClarity_E ,
   pro.VQClarity_S = @VQClarity_S ,
   pro.VQBias_I = @VQBias_I ,
   pro.VQBias_E = @VQBias_E ,
   pro.VQBias_S = @VQBias_S ,
   pro.SQClarity_I = @SQClarity_I ,
   pro.SQClarity_E = @SQClarity_E ,
   pro.SQClarity_S = @SQClarity_S ,
   pro.SQBias_I = @SQBias_I ,
   pro.SQBias_E = @SQBias_E ,
   pro.SQBias_S = @SQBias_S ,
   pro.xVQClarity_I = @xVQClarity_I ,
   pro.xVQClarity_E = @xVQClarity_E ,
   pro.xVQClarity_S = @xVQClarity_S ,
   pro.xVQBias_I = @xVQBias_I ,
   pro.xVQBias_E = @xVQBias_E ,
   pro.xVQBias_S = @xVQBias_S ,
   pro.xSQClarity_I = @xSQClarity_I ,
   pro.xSQClarity_E = @xSQClarity_E ,
   pro.xSQClarity_S = @xSQClarity_S ,
   pro.xSQBias_I = @xSQBias_I ,
   pro.xSQBias_E = @xSQBias_E ,
   pro.xSQBias_S = @xSQBias_S
FROM Profile AS pro
WHERE pro.ProfileID = @ProfileID

GO