EXEC [dbo].pts_CheckProc 'pts_Coption_Fetch'
 GO

CREATE PROCEDURE [dbo].pts_Coption_Fetch ( 
   @CoptionID int,
   @CompanyID int OUTPUT,
   @InitPrice money OUTPUT,
   @Price money OUTPUT,
   @Price2 money OUTPUT,
   @Price3 money OUTPUT,
   @Discount money OUTPUT,
   @Retail money OUTPUT,
   @Retail2 money OUTPUT,
   @Retail3 money OUTPUT,
   @BusPrice money OUTPUT,
   @BusRetail money OUTPUT,
   @BusAccts int OUTPUT,
   @BusAcctPrice money OUTPUT,
   @BusAcctRetail money OUTPUT,
   @IsCatalog bit OUTPUT,
   @IsDiscount bit OUTPUT,
   @Billing int OUTPUT,
   @CommRate money OUTPUT,
   @PromoCode int OUTPUT,
   @AccessLimit varchar (50) OUTPUT,
   @QuizLimit int OUTPUT,
   @MemberLimit int OUTPUT,
   @TrialDays int OUTPUT,
   @IsTrialPayment bit OUTPUT,
   @IsSignIn bit OUTPUT,
   @IsJoinNow bit OUTPUT,
   @IsNewEmail bit OUTPUT,
   @IsBusAcct bit OUTPUT,
   @IsFree bit OUTPUT,
   @RefName nvarchar (20) OUTPUT,
   @NewMemberOrgs varchar (20) OUTPUT,
   @TBPage varchar (20) OUTPUT,
   @Languages varchar (200) OUTPUT,
   @UploadURL varchar (40) OUTPUT,
   @SetupFee money OUTPUT,
   @IsSalesDefault bit OUTPUT,
   @ProjectsDefault int OUTPUT,
   @DocSizeLimit int OUTPUT,
   @FreeOptions varchar (40) OUTPUT,
   @EasyOptions varchar (40) OUTPUT,
   @Options varchar (50) OUTPUT,
   @Options2 varchar (50) OUTPUT,
   @Options3 varchar (50) OUTPUT,
   @Options4 varchar (40) OUTPUT,
   @Options5 varchar (40) OUTPUT,
   @Options6 varchar (40) OUTPUT,
   @Options7 varchar (40) OUTPUT,
   @Options8 varchar (40) OUTPUT,
   @FreeName nvarchar (40) OUTPUT,
   @PaidName nvarchar (40) OUTPUT,
   @PaidName2 nvarchar (40) OUTPUT,
   @PaidName3 nvarchar (40) OUTPUT,
   @Identify int OUTPUT,
   @Identification nvarchar (500) OUTPUT,
   @MerchantCardType int OUTPUT,
   @MerchantCheckType int OUTPUT,
   @MerchantCardAcct nvarchar (100) OUTPUT,
   @MerchantCheckAcct nvarchar (100) OUTPUT,
   @WalletType varchar (20) OUTPUT,
   @WalletAcct varchar (100) OUTPUT,
   @PayoutProcessors varchar (20) OUTPUT,
   @PaymentOptions varchar (15) OUTPUT,
   @MiscPay1 nvarchar (30) OUTPUT,
   @MiscPay2 nvarchar (30) OUTPUT,
   @MiscPay3 nvarchar (30) OUTPUT,
   @IPLimit int OUTPUT,
   @InputOptions nvarchar (1000) OUTPUT,
   @GAAcct varchar (50) OUTPUT,
   @Countries varchar (100) OUTPUT,
   @MenuColors varchar (200) OUTPUT,
   @Portal varchar (20) OUTPUT,
   @Shopping varchar (20) OUTPUT,
   @UserID int
      )
AS


SET NOCOUNT ON


SELECT   @CompanyID = cop.CompanyID ,
   @InitPrice = cop.InitPrice ,
   @Price = cop.Price ,
   @Price2 = cop.Price2 ,
   @Price3 = cop.Price3 ,
   @Discount = cop.Discount ,
   @Retail = cop.Retail ,
   @Retail2 = cop.Retail2 ,
   @Retail3 = cop.Retail3 ,
   @BusPrice = cop.BusPrice ,
   @BusRetail = cop.BusRetail ,
   @BusAccts = cop.BusAccts ,
   @BusAcctPrice = cop.BusAcctPrice ,
   @BusAcctRetail = cop.BusAcctRetail ,
   @IsCatalog = cop.IsCatalog ,
   @IsDiscount = cop.IsDiscount ,
   @Billing = cop.Billing ,
   @CommRate = cop.CommRate ,
   @PromoCode = cop.PromoCode ,
   @AccessLimit = cop.AccessLimit ,
   @QuizLimit = cop.QuizLimit ,
   @MemberLimit = cop.MemberLimit ,
   @TrialDays = cop.TrialDays ,
   @IsTrialPayment = cop.IsTrialPayment ,
   @IsSignIn = cop.IsSignIn ,
   @IsJoinNow = cop.IsJoinNow ,
   @IsNewEmail = cop.IsNewEmail ,
   @IsBusAcct = cop.IsBusAcct ,
   @IsFree = cop.IsFree ,
   @RefName = cop.RefName ,
   @NewMemberOrgs = cop.NewMemberOrgs ,
   @TBPage = cop.TBPage ,
   @Languages = cop.Languages ,
   @UploadURL = cop.UploadURL ,
   @SetupFee = cop.SetupFee ,
   @IsSalesDefault = cop.IsSalesDefault ,
   @ProjectsDefault = cop.ProjectsDefault ,
   @DocSizeLimit = cop.DocSizeLimit ,
   @FreeOptions = cop.FreeOptions ,
   @EasyOptions = cop.EasyOptions ,
   @Options = cop.Options ,
   @Options2 = cop.Options2 ,
   @Options3 = cop.Options3 ,
   @Options4 = cop.Options4 ,
   @Options5 = cop.Options5 ,
   @Options6 = cop.Options6 ,
   @Options7 = cop.Options7 ,
   @Options8 = cop.Options8 ,
   @FreeName = cop.FreeName ,
   @PaidName = cop.PaidName ,
   @PaidName2 = cop.PaidName2 ,
   @PaidName3 = cop.PaidName3 ,
   @Identify = cop.Identify ,
   @Identification = cop.Identification ,
   @MerchantCardType = cop.MerchantCardType ,
   @MerchantCheckType = cop.MerchantCheckType ,
   @MerchantCardAcct = cop.MerchantCardAcct ,
   @MerchantCheckAcct = cop.MerchantCheckAcct ,
   @WalletType = cop.WalletType ,
   @WalletAcct = cop.WalletAcct ,
   @PayoutProcessors = cop.PayoutProcessors ,
   @PaymentOptions = cop.PaymentOptions ,
   @MiscPay1 = cop.MiscPay1 ,
   @MiscPay2 = cop.MiscPay2 ,
   @MiscPay3 = cop.MiscPay3 ,
   @IPLimit = cop.IPLimit ,
   @InputOptions = cop.InputOptions ,
   @GAAcct = cop.GAAcct ,
   @Countries = cop.Countries ,
   @MenuColors = cop.MenuColors ,
   @Portal = cop.Portal ,
   @Shopping = cop.Shopping
FROM Coption AS cop (NOLOCK)
WHERE cop.CoptionID = @CoptionID

GO