EXEC [dbo].pts_CheckProc 'pts_BarterAd_Fetch'
 GO

CREATE PROCEDURE [dbo].pts_BarterAd_Fetch ( 
   @BarterAdID int,
   @ConsumerID int OUTPUT,
   @BarterArea1ID int OUTPUT,
   @BarterArea2ID int OUTPUT,
   @BarterCategoryID int OUTPUT,
   @Title nvarchar (100) OUTPUT,
   @Status int OUTPUT,
   @PostDate datetime OUTPUT,
   @UpdateDate datetime OUTPUT,
   @EndDate datetime OUTPUT,
   @Price money OUTPUT,
   @Location nvarchar (40) OUTPUT,
   @Zip nvarchar (10) OUTPUT,
   @Description nvarchar (4000) OUTPUT,
   @Language nvarchar (10) OUTPUT,
   @ContactName nvarchar (40) OUTPUT,
   @ContactEmail nvarchar (80) OUTPUT,
   @ContactPhone nvarchar (40) OUTPUT,
   @IsEmail bit OUTPUT,
   @IsPhone bit OUTPUT,
   @IsText bit OUTPUT,
   @IsMore bit OUTPUT,
   @IsMap bit OUTPUT,
   @IsContact bit OUTPUT,
   @IsDealer bit OUTPUT,
   @MapStreet1 nvarchar (60) OUTPUT,
   @MapStreet2 nvarchar (60) OUTPUT,
   @MapCity nvarchar (30) OUTPUT,
   @MapZip nvarchar (10) OUTPUT,
   @Options varchar (20) OUTPUT,
   @Payments varchar (20) OUTPUT,
   @Condition int OUTPUT,
   @Images int OUTPUT,
   @GeoCode varchar (30) OUTPUT,
   @T1 nvarchar (40) OUTPUT,
   @T2 nvarchar (40) OUTPUT,
   @T3 nvarchar (40) OUTPUT,
   @T4 nvarchar (40) OUTPUT,
   @T5 nvarchar (40) OUTPUT,
   @N1 int OUTPUT,
   @N2 int OUTPUT,
   @N3 int OUTPUT,
   @N4 int OUTPUT,
   @N5 int OUTPUT,
   @L1 tinyint OUTPUT,
   @L2 tinyint OUTPUT,
   @L3 tinyint OUTPUT,
   @L4 tinyint OUTPUT,
   @L5 tinyint OUTPUT,
   @L6 tinyint OUTPUT,
   @L7 tinyint OUTPUT,
   @L8 tinyint OUTPUT,
   @L9 tinyint OUTPUT,
   @L10 tinyint OUTPUT,
   @Y1 bit OUTPUT,
   @Y2 bit OUTPUT,
   @Y3 bit OUTPUT,
   @Y4 bit OUTPUT,
   @Y5 bit OUTPUT,
   @Y6 bit OUTPUT,
   @Y7 bit OUTPUT,
   @Y8 bit OUTPUT,
   @Y9 bit OUTPUT,
   @Y10 bit OUTPUT,
   @D1 datetime OUTPUT,
   @D2 datetime OUTPUT,
   @D3 datetime OUTPUT,
   @D4 datetime OUTPUT,
   @D5 datetime OUTPUT,
   @UserID int
      )
AS


SET NOCOUNT ON


SELECT   @ConsumerID = bad.ConsumerID ,
   @BarterArea1ID = bad.BarterArea1ID ,
   @BarterArea2ID = bad.BarterArea2ID ,
   @BarterCategoryID = bad.BarterCategoryID ,
   @Title = bad.Title ,
   @Status = bad.Status ,
   @PostDate = bad.PostDate ,
   @UpdateDate = bad.UpdateDate ,
   @EndDate = bad.EndDate ,
   @Price = bad.Price ,
   @Location = bad.Location ,
   @Zip = bad.Zip ,
   @Description = bad.Description ,
   @Language = bad.Language ,
   @ContactName = bad.ContactName ,
   @ContactEmail = bad.ContactEmail ,
   @ContactPhone = bad.ContactPhone ,
   @IsEmail = bad.IsEmail ,
   @IsPhone = bad.IsPhone ,
   @IsText = bad.IsText ,
   @IsMore = bad.IsMore ,
   @IsMap = bad.IsMap ,
   @IsContact = bad.IsContact ,
   @IsDealer = bad.IsDealer ,
   @MapStreet1 = bad.MapStreet1 ,
   @MapStreet2 = bad.MapStreet2 ,
   @MapCity = bad.MapCity ,
   @MapZip = bad.MapZip ,
   @Options = bad.Options ,
   @Payments = bad.Payments ,
   @Condition = bad.Condition ,
   @Images = bad.Images ,
   @GeoCode = bad.GeoCode ,
   @T1 = bad.T1 ,
   @T2 = bad.T2 ,
   @T3 = bad.T3 ,
   @T4 = bad.T4 ,
   @T5 = bad.T5 ,
   @N1 = bad.N1 ,
   @N2 = bad.N2 ,
   @N3 = bad.N3 ,
   @N4 = bad.N4 ,
   @N5 = bad.N5 ,
   @L1 = bad.L1 ,
   @L2 = bad.L2 ,
   @L3 = bad.L3 ,
   @L4 = bad.L4 ,
   @L5 = bad.L5 ,
   @L6 = bad.L6 ,
   @L7 = bad.L7 ,
   @L8 = bad.L8 ,
   @L9 = bad.L9 ,
   @L10 = bad.L10 ,
   @Y1 = bad.Y1 ,
   @Y2 = bad.Y2 ,
   @Y3 = bad.Y3 ,
   @Y4 = bad.Y4 ,
   @Y5 = bad.Y5 ,
   @Y6 = bad.Y6 ,
   @Y7 = bad.Y7 ,
   @Y8 = bad.Y8 ,
   @Y9 = bad.Y9 ,
   @Y10 = bad.Y10 ,
   @D1 = bad.D1 ,
   @D2 = bad.D2 ,
   @D3 = bad.D3 ,
   @D4 = bad.D4 ,
   @D5 = bad.D5
FROM BarterAd AS bad (NOLOCK)
WHERE bad.BarterAdID = @BarterAdID

GO