EXEC [dbo].pts_CheckProc 'pts_Merchant_Fetch'
 GO

CREATE PROCEDURE [dbo].pts_Merchant_Fetch ( 
   @MerchantID int,
   @MemberID int OUTPUT,
   @BillingID int OUTPUT,
   @PayoutID int OUTPUT,
   @CountryID int OUTPUT,
   @SweepID int OUTPUT,
   @MemberNameLast nvarchar (30) OUTPUT,
   @MemberNameFirst nvarchar (30) OUTPUT,
   @MemberName nvarchar (61) OUTPUT,
   @CountryName nvarchar (50) OUTPUT,
   @MerchantName nvarchar (80) OUTPUT,
   @NameLast nvarchar (30) OUTPUT,
   @NameFirst nvarchar (30) OUTPUT,
   @Email nvarchar (80) OUTPUT,
   @Email2 nvarchar (80) OUTPUT,
   @Email3 nvarchar (80) OUTPUT,
   @Phone nvarchar (30) OUTPUT,
   @Phone2 nvarchar (30) OUTPUT,
   @Password nvarchar (20) OUTPUT,
   @Password2 nvarchar (20) OUTPUT,
   @Password3 nvarchar (20) OUTPUT,
   @Password4 nvarchar (20) OUTPUT,
   @Status int OUTPUT,
   @Street1 nvarchar (60) OUTPUT,
   @Street2 nvarchar (60) OUTPUT,
   @City nvarchar (30) OUTPUT,
   @State nvarchar (30) OUTPUT,
   @Zip nvarchar (20) OUTPUT,
   @Referrals int OUTPUT,
   @Referrals2 int OUTPUT,
   @VisitDate datetime OUTPUT,
   @IsOrg bit OUTPUT,
   @IsAwards bit OUTPUT,
   @EnrollDate datetime OUTPUT,
   @BillDate datetime OUTPUT,
   @BillDays int OUTPUT,
   @Image nvarchar (40) OUTPUT,
   @Description nvarchar (2000) OUTPUT,
   @Terms nvarchar (100) OUTPUT,
   @Options varchar (20) OUTPUT,
   @StoreOptions varchar (20) OUTPUT,
   @Colors varchar (100) OUTPUT,
   @Rating int OUTPUT,
   @CurrencyCode varchar (3) OUTPUT,
   @Processor int OUTPUT,
   @Payment varchar (1000) OUTPUT,
   @UserKey varchar (40) OUTPUT,
   @UserKey3 varchar (40) OUTPUT,
   @UserKey4 varchar (40) OUTPUT,
   @UserCode varchar (10) OUTPUT,
   @Access varchar (80) OUTPUT,
   @PromoLimit int OUTPUT,
   @SweepRate int OUTPUT,
   @TimeZone int OUTPUT,
   @GeoCode varchar (30) OUTPUT,
   @ReferRate int OUTPUT,
   @UserID int
      )
AS


SET NOCOUNT ON


SELECT   @MemberID = mer.MemberID ,
   @BillingID = mer.BillingID ,
   @PayoutID = mer.PayoutID ,
   @CountryID = mer.CountryID ,
   @SweepID = mer.SweepID ,
   @MemberNameLast = me.NameLast ,
   @MemberNameFirst = me.NameFirst ,
   @MemberName = LTRIM(RTRIM(me.NameFirst)) +  ' '  + LTRIM(RTRIM(me.NameLast)) ,
   @CountryName = cou.CountryName ,
   @MerchantName = mer.MerchantName ,
   @NameLast = mer.NameLast ,
   @NameFirst = mer.NameFirst ,
   @Email = mer.Email ,
   @Email2 = mer.Email2 ,
   @Email3 = mer.Email3 ,
   @Phone = mer.Phone ,
   @Phone2 = mer.Phone2 ,
   @Password = mer.Password ,
   @Password2 = mer.Password2 ,
   @Password3 = mer.Password3 ,
   @Password4 = mer.Password4 ,
   @Status = mer.Status ,
   @Street1 = mer.Street1 ,
   @Street2 = mer.Street2 ,
   @City = mer.City ,
   @State = mer.State ,
   @Zip = mer.Zip ,
   @Referrals = mer.Referrals ,
   @Referrals2 = mer.Referrals2 ,
   @VisitDate = mer.VisitDate ,
   @IsOrg = mer.IsOrg ,
   @IsAwards = mer.IsAwards ,
   @EnrollDate = mer.EnrollDate ,
   @BillDate = mer.BillDate ,
   @BillDays = mer.BillDays ,
   @Image = mer.Image ,
   @Description = mer.Description ,
   @Terms = mer.Terms ,
   @Options = mer.Options ,
   @StoreOptions = mer.StoreOptions ,
   @Colors = mer.Colors ,
   @Rating = mer.Rating ,
   @CurrencyCode = mer.CurrencyCode ,
   @Processor = mer.Processor ,
   @Payment = mer.Payment ,
   @UserKey = mer.UserKey ,
   @UserKey3 = mer.UserKey3 ,
   @UserKey4 = mer.UserKey4 ,
   @UserCode = mer.UserCode ,
   @Access = mer.Access ,
   @PromoLimit = mer.PromoLimit ,
   @SweepRate = mer.SweepRate ,
   @TimeZone = mer.TimeZone ,
   @GeoCode = mer.GeoCode ,
   @ReferRate = mer.ReferRate
FROM Merchant AS mer (NOLOCK)
LEFT OUTER JOIN Member AS me (NOLOCK) ON (mer.MemberID = me.MemberID)
LEFT OUTER JOIN Country AS cou (NOLOCK) ON (mer.CountryID = cou.CountryID)
WHERE mer.MerchantID = @MerchantID

GO