EXEC [dbo].pts_CheckProc 'pts_Product_Fetch'
 GO

CREATE PROCEDURE [dbo].pts_Product_Fetch ( 
   @ProductID int,
   @CompanyID int OUTPUT,
   @ProductTypeID int OUTPUT,
   @ProductTypeName nvarchar (40) OUTPUT,
   @ProductName nvarchar (40) OUTPUT,
   @Image nvarchar (40) OUTPUT,
   @Price money OUTPUT,
   @OriginalPrice money OUTPUT,
   @IsTaxable bit OUTPUT,
   @TaxRate money OUTPUT,
   @Tax money OUTPUT,
   @Description nvarchar (2000) OUTPUT,
   @Seq int OUTPUT,
   @IsActive bit OUTPUT,
   @IsPrivate bit OUTPUT,
   @IsPublic bit OUTPUT,
   @NoQty bit OUTPUT,
   @Data nvarchar (80) OUTPUT,
   @Email nvarchar (80) OUTPUT,
   @InputOptions nvarchar (2000) OUTPUT,
   @Ship1 money OUTPUT,
   @Ship2 money OUTPUT,
   @Ship3 money OUTPUT,
   @Ship4 money OUTPUT,
   @Ship1a money OUTPUT,
   @Ship2a money OUTPUT,
   @Ship3a money OUTPUT,
   @Ship4a money OUTPUT,
   @Fulfill int OUTPUT,
   @Recur int OUTPUT,
   @RecurTerm varchar (10) OUTPUT,
   @CommPlan int OUTPUT,
   @BV money OUTPUT,
   @QV money OUTPUT,
   @Code varchar (10) OUTPUT,
   @Inventory int OUTPUT,
   @InStock int OUTPUT,
   @ReOrder int OUTPUT,
   @IsShip bit OUTPUT,
   @OrderMin int OUTPUT,
   @OrderMax int OUTPUT,
   @OrderMul int OUTPUT,
   @OrderGrp varchar (10) OUTPUT,
   @Attribute1 varchar (15) OUTPUT,
   @Attribute2 varchar (15) OUTPUT,
   @Attribute3 varchar (15) OUTPUT,
   @Levels varchar (5) OUTPUT,
   @FulFillInfo varchar (100) OUTPUT,
   @UserID int
      )
AS


SET NOCOUNT ON


SELECT   @CompanyID = pd.CompanyID ,
   @ProductTypeID = pd.ProductTypeID ,
   @ProductTypeName = pdt.ProductTypeName ,
   @ProductName = pd.ProductName ,
   @Image = pd.Image ,
   @Price = pd.Price ,
   @OriginalPrice = pd.OriginalPrice ,
   @IsTaxable = pd.IsTaxable ,
   @TaxRate = pd.TaxRate ,
   @Tax = pd.Tax ,
   @Description = pd.Description ,
   @Seq = pd.Seq ,
   @IsActive = pd.IsActive ,
   @IsPrivate = pd.IsPrivate ,
   @IsPublic = pd.IsPublic ,
   @NoQty = pd.NoQty ,
   @Data = pd.Data ,
   @Email = pd.Email ,
   @InputOptions = pd.InputOptions ,
   @Ship1 = pd.Ship1 ,
   @Ship2 = pd.Ship2 ,
   @Ship3 = pd.Ship3 ,
   @Ship4 = pd.Ship4 ,
   @Ship1a = pd.Ship1a ,
   @Ship2a = pd.Ship2a ,
   @Ship3a = pd.Ship3a ,
   @Ship4a = pd.Ship4a ,
   @Fulfill = pd.Fulfill ,
   @Recur = pd.Recur ,
   @RecurTerm = pd.RecurTerm ,
   @CommPlan = pd.CommPlan ,
   @BV = pd.BV ,
   @QV = pd.QV ,
   @Code = pd.Code ,
   @Inventory = pd.Inventory ,
   @InStock = pd.InStock ,
   @ReOrder = pd.ReOrder ,
   @IsShip = pd.IsShip ,
   @OrderMin = pd.OrderMin ,
   @OrderMax = pd.OrderMax ,
   @OrderMul = pd.OrderMul ,
   @OrderGrp = pd.OrderGrp ,
   @Attribute1 = pd.Attribute1 ,
   @Attribute2 = pd.Attribute2 ,
   @Attribute3 = pd.Attribute3 ,
   @Levels = pd.Levels ,
   @FulFillInfo = pd.FulFillInfo
FROM Product AS pd (NOLOCK)
LEFT OUTER JOIN ProductType AS pdt (NOLOCK) ON (pd.ProductTypeID = pdt.ProductTypeID)
WHERE pd.ProductID = @ProductID

GO