EXEC [dbo].pts_CheckProc 'pts_Member_Fetch'
 GO

CREATE PROCEDURE [dbo].pts_Member_Fetch ( 
   @MemberID int,
   @AuthUserID int OUTPUT,
   @WebsiteID int OUTPUT,
   @CompanyID int OUTPUT,
   @PromoID int OUTPUT,
   @BillingID int OUTPUT,
   @PayID int OUTPUT,
   @ReferralID int OUTPUT,
   @SponsorID int OUTPUT,
   @Sponsor2ID int OUTPUT,
   @Sponsor3ID int OUTPUT,
   @MentorID int OUTPUT,
   @UserGroup int OUTPUT,
   @UserStatus int OUTPUT,
   @Logon nvarchar (80) OUTPUT,
   @CompanyName nvarchar (60) OUTPUT,
   @NameLast nvarchar (30) OUTPUT,
   @NameFirst nvarchar (30) OUTPUT,
   @MemberName nvarchar (62) OUTPUT,
   @BV money OUTPUT,
   @QV money OUTPUT,
   @BV2 money OUTPUT,
   @QV2 money OUTPUT,
   @BV3 money OUTPUT,
   @QV3 money OUTPUT,
   @BV4 money OUTPUT,
   @QV4 money OUTPUT,
   @Qualify int OUTPUT,
   @QualifyDate datetime OUTPUT,
   @Email nvarchar (80) OUTPUT,
   @Email2 nvarchar (80) OUTPUT,
   @Phone1 nvarchar (30) OUTPUT,
   @Phone2 nvarchar (30) OUTPUT,
   @Fax nvarchar (30) OUTPUT,
   @Status int OUTPUT,
   @Level int OUTPUT,
   @Newsletter int OUTPUT,
   @EnrollDate datetime OUTPUT,
   @EndDate datetime OUTPUT,
   @InitPrice money OUTPUT,
   @Price money OUTPUT,
   @Retail money OUTPUT,
   @BusAccts int OUTPUT,
   @BusAcctPrice money OUTPUT,
   @BusAcctRetail money OUTPUT,
   @IsDiscount bit OUTPUT,
   @Discount money OUTPUT,
   @IsCompany bit OUTPUT,
   @Billing int OUTPUT,
   @AccessLimit varchar (50) OUTPUT,
   @QuizLimit int OUTPUT,
   @Reference varchar (15) OUTPUT,
   @Referral varchar (15) OUTPUT,
   @TrialDays int OUTPUT,
   @MasterID int OUTPUT,
   @IsIncluded bit OUTPUT,
   @IsMaster bit OUTPUT,
   @MasterPrice money OUTPUT,
   @MasterMembers int OUTPUT,
   @MaxMembers int OUTPUT,
   @VisitDate datetime OUTPUT,
   @TaxIDType int OUTPUT,
   @TaxID nvarchar (15) OUTPUT,
   @AutoShipDate datetime OUTPUT,
   @PaidDate datetime OUTPUT,
   @StatusDate datetime OUTPUT,
   @StatusChange int OUTPUT,
   @LevelChange int OUTPUT,
   @IsRemoved bit OUTPUT,
   @GroupID int OUTPUT,
   @Role nvarchar (15) OUTPUT,
   @Secure int OUTPUT,
   @Options varchar (20) OUTPUT,
   @Options2 varchar (40) OUTPUT,
   @Pos int OUTPUT,
   @Signature nvarchar (1000) OUTPUT,
   @SocNet varchar (200) OUTPUT,
   @ConfLine varchar (40) OUTPUT,
   @NotifyMentor varchar (10) OUTPUT,
   @Image varchar (15) OUTPUT,
   @Identification nvarchar (150) OUTPUT,
   @Title int OUTPUT,
   @Title2 int OUTPUT,
   @MinTitle int OUTPUT,
   @TitleDate datetime OUTPUT,
   @InputValues nvarchar (1000) OUTPUT,
   @Icons varchar (20) OUTPUT,
   @IsMsg int OUTPUT,
   @Timezone int OUTPUT,
   @Process int OUTPUT,
   @UserID int
      )
AS


SET NOCOUNT ON


SELECT   @AuthUserID = me.AuthUserID ,
   @WebsiteID = me.WebsiteID ,
   @CompanyID = me.CompanyID ,
   @PromoID = me.PromoID ,
   @BillingID = me.BillingID ,
   @PayID = me.PayID ,
   @ReferralID = me.ReferralID ,
   @SponsorID = me.SponsorID ,
   @Sponsor2ID = me.Sponsor2ID ,
   @Sponsor3ID = me.Sponsor3ID ,
   @MentorID = me.MentorID ,
   @UserGroup = au.UserGroup ,
   @UserStatus = au.UserStatus ,
   @Logon = au.Logon ,
   @CompanyName = me.CompanyName ,
   @NameLast = me.NameLast ,
   @NameFirst = me.NameFirst ,
   @MemberName = LTRIM(RTRIM(me.NameLast)) +  ', '  + LTRIM(RTRIM(me.NameFirst)) ,
   @BV = me.BV ,
   @QV = me.QV ,
   @BV2 = me.BV2 ,
   @QV2 = me.QV2 ,
   @BV3 = me.BV3 ,
   @QV3 = me.QV3 ,
   @BV4 = me.BV4 ,
   @QV4 = me.QV4 ,
   @Qualify = me.Qualify ,
   @QualifyDate = me.QualifyDate ,
   @Email = me.Email ,
   @Email2 = me.Email2 ,
   @Phone1 = me.Phone1 ,
   @Phone2 = me.Phone2 ,
   @Fax = me.Fax ,
   @Status = me.Status ,
   @Level = me.Level ,
   @Newsletter = me.Newsletter ,
   @EnrollDate = me.EnrollDate ,
   @EndDate = me.EndDate ,
   @InitPrice = me.InitPrice ,
   @Price = me.Price ,
   @Retail = me.Retail ,
   @BusAccts = me.BusAccts ,
   @BusAcctPrice = me.BusAcctPrice ,
   @BusAcctRetail = me.BusAcctRetail ,
   @IsDiscount = me.IsDiscount ,
   @Discount = me.Discount ,
   @IsCompany = me.IsCompany ,
   @Billing = me.Billing ,
   @AccessLimit = me.AccessLimit ,
   @QuizLimit = me.QuizLimit ,
   @Reference = me.Reference ,
   @Referral = me.Referral ,
   @TrialDays = me.TrialDays ,
   @MasterID = me.MasterID ,
   @IsIncluded = me.IsIncluded ,
   @IsMaster = me.IsMaster ,
   @MasterPrice = me.MasterPrice ,
   @MasterMembers = me.MasterMembers ,
   @MaxMembers = me.MaxMembers ,
   @VisitDate = me.VisitDate ,
   @TaxIDType = me.TaxIDType ,
   @TaxID = me.TaxID ,
   @AutoShipDate = me.AutoShipDate ,
   @PaidDate = me.PaidDate ,
   @StatusDate = me.StatusDate ,
   @StatusChange = me.StatusChange ,
   @LevelChange = me.LevelChange ,
   @IsRemoved = me.IsRemoved ,
   @GroupID = me.GroupID ,
   @Role = me.Role ,
   @Secure = me.Secure ,
   @Options = me.Options ,
   @Options2 = me.Options2 ,
   @Pos = me.Pos ,
   @Signature = me.Signature ,
   @SocNet = me.SocNet ,
   @ConfLine = me.ConfLine ,
   @NotifyMentor = me.NotifyMentor ,
   @Image = me.Image ,
   @Identification = me.Identification ,
   @Title = me.Title ,
   @Title2 = me.Title2 ,
   @MinTitle = me.MinTitle ,
   @TitleDate = me.TitleDate ,
   @InputValues = me.InputValues ,
   @Icons = me.Icons ,
   @IsMsg = me.IsMsg ,
   @Timezone = me.Timezone ,
   @Process = me.Process
FROM Member AS me (NOLOCK)
LEFT OUTER JOIN AuthUser AS au (NOLOCK) ON (me.AuthUserID = au.AuthUserID)
WHERE me.MemberID = @MemberID

GO