EXEC [dbo].pts_CheckProc 'pts_Coption_Add'
 GO

CREATE PROCEDURE [dbo].pts_Coption_Add ( 
   @CoptionID int OUTPUT,
   @CompanyID int,
   @InitPrice money,
   @Price money,
   @Price2 money,
   @Price3 money,
   @Discount money,
   @Retail money,
   @Retail2 money,
   @Retail3 money,
   @BusPrice money,
   @BusRetail money,
   @BusAccts int,
   @BusAcctPrice money,
   @BusAcctRetail money,
   @IsCatalog bit,
   @IsDiscount bit,
   @Billing int,
   @CommRate money,
   @PromoCode int,
   @AccessLimit varchar (50),
   @QuizLimit int,
   @MemberLimit int,
   @TrialDays int,
   @IsTrialPayment bit,
   @IsSignIn bit,
   @IsJoinNow bit,
   @IsNewEmail bit,
   @IsBusAcct bit,
   @IsFree bit,
   @RefName nvarchar (20),
   @NewMemberOrgs varchar (20),
   @TBPage varchar (20),
   @Languages varchar (200),
   @UploadURL varchar (40),
   @SetupFee money,
   @IsSalesDefault bit,
   @ProjectsDefault int,
   @DocSizeLimit int,
   @FreeOptions varchar (40),
   @EasyOptions varchar (40),
   @Options varchar (50),
   @Options2 varchar (50),
   @Options3 varchar (50),
   @Options4 varchar (40),
   @Options5 varchar (40),
   @Options6 varchar (40),
   @Options7 varchar (40),
   @Options8 varchar (40),
   @FreeName nvarchar (40),
   @PaidName nvarchar (40),
   @PaidName2 nvarchar (40),
   @PaidName3 nvarchar (40),
   @Identify int,
   @Identification nvarchar (500),
   @MerchantCardType int,
   @MerchantCheckType int,
   @MerchantCardAcct nvarchar (100),
   @MerchantCheckAcct nvarchar (100),
   @WalletType varchar (20),
   @WalletAcct varchar (100),
   @PayoutProcessors varchar (20),
   @PaymentOptions varchar (15),
   @MiscPay1 nvarchar (30),
   @MiscPay2 nvarchar (30),
   @MiscPay3 nvarchar (30),
   @IPLimit int,
   @InputOptions nvarchar (1000),
   @GAAcct varchar (50),
   @Countries varchar (100),
   @MenuColors varchar (200),
   @Portal varchar (20),
   @Shopping varchar (20),
   @UserID int
      )
AS

DECLARE @mNow datetime
DECLARE @mNewID int

SET NOCOUNT ON

SET @mNow = GETDATE()


INSERT INTO Coption (
            CompanyID , 
            InitPrice , 
            Price , 
            Price2 , 
            Price3 , 
            Discount , 
            Retail , 
            Retail2 , 
            Retail3 , 
            BusPrice , 
            BusRetail , 
            BusAccts , 
            BusAcctPrice , 
            BusAcctRetail , 
            IsCatalog , 
            IsDiscount , 
            Billing , 
            CommRate , 
            PromoCode , 
            AccessLimit , 
            QuizLimit , 
            MemberLimit , 
            TrialDays , 
            IsTrialPayment , 
            IsSignIn , 
            IsJoinNow , 
            IsNewEmail , 
            IsBusAcct , 
            IsFree , 
            RefName , 
            NewMemberOrgs , 
            TBPage , 
            Languages , 
            UploadURL , 
            SetupFee , 
            IsSalesDefault , 
            ProjectsDefault , 
            DocSizeLimit , 
            FreeOptions , 
            EasyOptions , 
            Options , 
            Options2 , 
            Options3 , 
            Options4 , 
            Options5 , 
            Options6 , 
            Options7 , 
            Options8 , 
            FreeName , 
            PaidName , 
            PaidName2 , 
            PaidName3 , 
            Identify , 
            Identification , 
            MerchantCardType , 
            MerchantCheckType , 
            MerchantCardAcct , 
            MerchantCheckAcct , 
            WalletType , 
            WalletAcct , 
            PayoutProcessors , 
            PaymentOptions , 
            MiscPay1 , 
            MiscPay2 , 
            MiscPay3 , 
            IPLimit , 
            InputOptions , 
            GAAcct , 
            Countries , 
            MenuColors , 
            Portal , 
            Shopping
            )
VALUES (
            @CompanyID ,
            @InitPrice ,
            @Price ,
            @Price2 ,
            @Price3 ,
            @Discount ,
            @Retail ,
            @Retail2 ,
            @Retail3 ,
            @BusPrice ,
            @BusRetail ,
            @BusAccts ,
            @BusAcctPrice ,
            @BusAcctRetail ,
            @IsCatalog ,
            @IsDiscount ,
            @Billing ,
            @CommRate ,
            @PromoCode ,
            @AccessLimit ,
            @QuizLimit ,
            @MemberLimit ,
            @TrialDays ,
            @IsTrialPayment ,
            @IsSignIn ,
            @IsJoinNow ,
            @IsNewEmail ,
            @IsBusAcct ,
            @IsFree ,
            @RefName ,
            @NewMemberOrgs ,
            @TBPage ,
            @Languages ,
            @UploadURL ,
            @SetupFee ,
            @IsSalesDefault ,
            @ProjectsDefault ,
            @DocSizeLimit ,
            @FreeOptions ,
            @EasyOptions ,
            @Options ,
            @Options2 ,
            @Options3 ,
            @Options4 ,
            @Options5 ,
            @Options6 ,
            @Options7 ,
            @Options8 ,
            @FreeName ,
            @PaidName ,
            @PaidName2 ,
            @PaidName3 ,
            @Identify ,
            @Identification ,
            @MerchantCardType ,
            @MerchantCheckType ,
            @MerchantCardAcct ,
            @MerchantCheckAcct ,
            @WalletType ,
            @WalletAcct ,
            @PayoutProcessors ,
            @PaymentOptions ,
            @MiscPay1 ,
            @MiscPay2 ,
            @MiscPay3 ,
            @IPLimit ,
            @InputOptions ,
            @GAAcct ,
            @Countries ,
            @MenuColors ,
            @Portal ,
            @Shopping            )

SET @mNewID = @@IDENTITY

SET @CoptionID = @mNewID

GO