EXEC [dbo].pts_CheckProc 'pts_Product_Add'
 GO

CREATE PROCEDURE [dbo].pts_Product_Add ( 
   @ProductID int OUTPUT,
   @CompanyID int,
   @ProductTypeID int,
   @ProductName nvarchar (40),
   @Image nvarchar (40),
   @Price money,
   @OriginalPrice money,
   @IsTaxable bit,
   @TaxRate money,
   @Tax money,
   @Description nvarchar (2000),
   @Seq int,
   @IsActive bit,
   @IsPrivate bit,
   @IsPublic bit,
   @NoQty bit,
   @Data nvarchar (80),
   @Email nvarchar (80),
   @InputOptions nvarchar (2000),
   @Ship1 money,
   @Ship2 money,
   @Ship3 money,
   @Ship4 money,
   @Ship1a money,
   @Ship2a money,
   @Ship3a money,
   @Ship4a money,
   @Fulfill int,
   @Recur int,
   @RecurTerm varchar (10),
   @CommPlan int,
   @BV money,
   @QV money,
   @Code varchar (10),
   @Inventory int,
   @InStock int,
   @ReOrder int,
   @IsShip bit,
   @OrderMin int,
   @OrderMax int,
   @OrderMul int,
   @OrderGrp varchar (10),
   @Attribute1 varchar (15),
   @Attribute2 varchar (15),
   @Attribute3 varchar (15),
   @Levels varchar (5),
   @FulFillInfo varchar (100),
   @UserID int
      )
AS

DECLARE @mNow datetime
DECLARE @mNewID int

SET NOCOUNT ON

SET @mNow = GETDATE()


INSERT INTO Product (
            CompanyID , 
            ProductTypeID , 
            ProductName , 
            Image , 
            Price , 
            OriginalPrice , 
            IsTaxable , 
            TaxRate , 
            Tax , 
            Description , 
            Seq , 
            IsActive , 
            IsPrivate , 
            IsPublic , 
            NoQty , 
            Data , 
            Email , 
            InputOptions , 
            Ship1 , 
            Ship2 , 
            Ship3 , 
            Ship4 , 
            Ship1a , 
            Ship2a , 
            Ship3a , 
            Ship4a , 
            Fulfill , 
            Recur , 
            RecurTerm , 
            CommPlan , 
            BV , 
            QV , 
            Code , 
            Inventory , 
            InStock , 
            ReOrder , 
            IsShip , 
            OrderMin , 
            OrderMax , 
            OrderMul , 
            OrderGrp , 
            Attribute1 , 
            Attribute2 , 
            Attribute3 , 
            Levels , 
            FulFillInfo
            )
VALUES (
            @CompanyID ,
            @ProductTypeID ,
            @ProductName ,
            @Image ,
            @Price ,
            @OriginalPrice ,
            @IsTaxable ,
            @TaxRate ,
            @Tax ,
            @Description ,
            @Seq ,
            @IsActive ,
            @IsPrivate ,
            @IsPublic ,
            @NoQty ,
            @Data ,
            @Email ,
            @InputOptions ,
            @Ship1 ,
            @Ship2 ,
            @Ship3 ,
            @Ship4 ,
            @Ship1a ,
            @Ship2a ,
            @Ship3a ,
            @Ship4a ,
            @Fulfill ,
            @Recur ,
            @RecurTerm ,
            @CommPlan ,
            @BV ,
            @QV ,
            @Code ,
            @Inventory ,
            @InStock ,
            @ReOrder ,
            @IsShip ,
            @OrderMin ,
            @OrderMax ,
            @OrderMul ,
            @OrderGrp ,
            @Attribute1 ,
            @Attribute2 ,
            @Attribute3 ,
            @Levels ,
            @FulFillInfo            )

SET @mNewID = @@IDENTITY

SET @ProductID = @mNewID

GO