EXEC [dbo].pts_CheckProc 'pts_Prospect_Update'
 GO

CREATE PROCEDURE [dbo].pts_Prospect_Update ( 
   @ProspectID int,
   @CompanyID int,
   @MemberID int,
   @SalesCampaignID int,
   @LeadCampaignID int,
   @PresentID int,
   @ProspectTypeID int,
   @EmailID int,
   @AffiliateID int,
   @NewsLetterID int,
   @ProspectName nvarchar (60),
   @Website nvarchar (80),
   @Description nvarchar (2000),
   @Representing nvarchar (20),
   @Potential money,
   @NameLast nvarchar (30),
   @NameFirst nvarchar (30),
   @Title nvarchar (30),
   @Email nvarchar (80),
   @Phone1 nvarchar (30),
   @Phone2 nvarchar (30),
   @Street nvarchar (60),
   @Unit nvarchar (40),
   @City nvarchar (30),
   @State nvarchar (30),
   @Zip nvarchar (20),
   @Country nvarchar (30),
   @Status int,
   @NextEvent int,
   @NextDate datetime,
   @NextTime varchar (8),
   @CreateDate datetime,
   @FBDate datetime,
   @CloseDate datetime,
   @DeadDate datetime,
   @Date1 datetime,
   @Date2 datetime,
   @Date3 datetime,
   @Date4 datetime,
   @Date5 datetime,
   @Date6 datetime,
   @Date7 datetime,
   @Date8 datetime,
   @Date9 datetime,
   @Date10 datetime,
   @ChangeDate datetime,
   @ChangeStatus int,
   @EmailDate datetime,
   @RSVP int,
   @EmailStatus int,
   @LeadViews int,
   @LeadPages varchar (10),
   @LeadReplies int,
   @PresentViews int,
   @PresentPages varchar (40),
   @NoDistribute bit,
   @DistributorID int,
   @DistributeDate datetime,
   @Priority nvarchar (4),
   @InputValues nvarchar (1000),
   @Source nvarchar (20),
   @Code int,
   @Reminder int,
   @RemindDate datetime,
   @TimeZone int,
   @BestTime int,
   @UserID int
      )
AS

DECLARE @mNow datetime

SET NOCOUNT ON

SET @mNow = GETDATE()

UPDATE pr
SET pr.CompanyID = @CompanyID ,
   pr.MemberID = @MemberID ,
   pr.SalesCampaignID = @SalesCampaignID ,
   pr.LeadCampaignID = @LeadCampaignID ,
   pr.PresentID = @PresentID ,
   pr.ProspectTypeID = @ProspectTypeID ,
   pr.EmailID = @EmailID ,
   pr.AffiliateID = @AffiliateID ,
   pr.NewsLetterID = @NewsLetterID ,
   pr.ProspectName = @ProspectName ,
   pr.Website = @Website ,
   pr.Description = @Description ,
   pr.Representing = @Representing ,
   pr.Potential = @Potential ,
   pr.NameLast = @NameLast ,
   pr.NameFirst = @NameFirst ,
   pr.Title = @Title ,
   pr.Email = @Email ,
   pr.Phone1 = @Phone1 ,
   pr.Phone2 = @Phone2 ,
   pr.Street = @Street ,
   pr.Unit = @Unit ,
   pr.City = @City ,
   pr.State = @State ,
   pr.Zip = @Zip ,
   pr.Country = @Country ,
   pr.Status = @Status ,
   pr.NextEvent = @NextEvent ,
   pr.NextDate = @NextDate ,
   pr.NextTime = @NextTime ,
   pr.CreateDate = @CreateDate ,
   pr.FBDate = @FBDate ,
   pr.CloseDate = @CloseDate ,
   pr.DeadDate = @DeadDate ,
   pr.Date1 = @Date1 ,
   pr.Date2 = @Date2 ,
   pr.Date3 = @Date3 ,
   pr.Date4 = @Date4 ,
   pr.Date5 = @Date5 ,
   pr.Date6 = @Date6 ,
   pr.Date7 = @Date7 ,
   pr.Date8 = @Date8 ,
   pr.Date9 = @Date9 ,
   pr.Date10 = @Date10 ,
   pr.ChangeDate = @ChangeDate ,
   pr.ChangeStatus = @ChangeStatus ,
   pr.EmailDate = @EmailDate ,
   pr.RSVP = @RSVP ,
   pr.EmailStatus = @EmailStatus ,
   pr.LeadViews = @LeadViews ,
   pr.LeadPages = @LeadPages ,
   pr.LeadReplies = @LeadReplies ,
   pr.PresentViews = @PresentViews ,
   pr.PresentPages = @PresentPages ,
   pr.NoDistribute = @NoDistribute ,
   pr.DistributorID = @DistributorID ,
   pr.DistributeDate = @DistributeDate ,
   pr.Priority = @Priority ,
   pr.InputValues = @InputValues ,
   pr.Source = @Source ,
   pr.Code = @Code ,
   pr.Reminder = @Reminder ,
   pr.RemindDate = @RemindDate ,
   pr.TimeZone = @TimeZone ,
   pr.BestTime = @BestTime
FROM Prospect AS pr
WHERE pr.ProspectID = @ProspectID

GO