EXEC [dbo].pts_CheckProc 'pts_Member_Add'
GO

CREATE PROCEDURE [dbo].pts_Member_Add
   @MemberID int OUTPUT,
   @AuthUserID int OUTPUT,
   @WebsiteID int,
   @CompanyID int,
   @PromoID int,
   @BillingID int,
   @PayID int,
   @ReferralID int,
   @SponsorID int,
   @Sponsor2ID int,
   @Sponsor3ID int,
   @MentorID int,
   @UserGroup int,
   @UserStatus int,
   @CompanyName nvarchar (60),
   @NameLast nvarchar (30),
   @NameFirst nvarchar (30),
   @BV money,
   @QV money,
   @BV2 money,
   @QV2 money,
   @BV3 money,
   @QV3 money,
   @BV4 money,
   @QV4 money,
   @Qualify int,
   @QualifyDate datetime,
   @Email nvarchar (80),
   @Email2 nvarchar (80),
   @Phone1 nvarchar (30),
   @Phone2 nvarchar (30),
   @Fax nvarchar (30),
   @Status int,
   @Level int,
   @Newsletter int,
   @EnrollDate datetime,
   @EndDate datetime,
   @InitPrice money,
   @Price money,
   @Retail money,
   @BusAccts int,
   @BusAcctPrice money,
   @BusAcctRetail money,
   @IsDiscount bit,
   @Discount money,
   @IsCompany bit,
   @Billing int,
   @AccessLimit varchar (50),
   @QuizLimit int,
   @Reference varchar (15),
   @Referral varchar (15),
   @TrialDays int,
   @MasterID int,
   @IsIncluded bit,
   @IsMaster bit,
   @MasterPrice money,
   @MasterMembers int,
   @MaxMembers int,
   @VisitDate datetime,
   @TaxIDType int,
   @TaxID nvarchar (15),
   @AutoShipDate datetime,
   @PaidDate datetime,
   @StatusDate datetime,
   @StatusChange int,
   @LevelChange int,
   @IsRemoved bit,
   @GroupID int,
   @Role nvarchar (15),
   @Secure int,
   @Options varchar (20),
   @Options2 varchar (40),
   @Pos int,
   @Signature nvarchar (1000),
   @SocNet varchar (200),
   @ConfLine varchar (40),
   @NotifyMentor varchar (10),
   @Image varchar (15),
   @Identification nvarchar (150),
   @Title int,
   @Title2 int,
   @MinTitle int,
   @TitleDate datetime,
   @InputValues nvarchar (1000),
   @Icons varchar (20),
   @IsMsg int,
   @Timezone int,
   @Process int,
   @NewLogon nvarchar (80),
   @NewPassword nvarchar (30),
   @Unit nvarchar (40),
   @UserID int
AS

DECLARE @mNow datetime, 
         @mNewID int, 
         @mAuthUserID int

SET NOCOUNT ON

SET @mNow = GETDATE()
SET @mAuthUserID = 0
IF ((@Email2 = ''))
   BEGIN
   SET @Email2 = @Email
   END

IF ((@UserGroup > 0))
   BEGIN
   EXEC pts_AuthUser_Add
      @NewLogon ,
      @NewPassword ,
      @Email ,
      @NameLast ,
      @NameFirst ,
      @UserGroup ,
      @UserStatus ,
      @UserID ,
      @mAuthUserID OUTPUT

   SET @AuthUserID = ISNULL(@mAuthUserID, 0)
   END

INSERT INTO Member (
            AuthUserID , 
            WebsiteID , 
            CompanyID , 
            PromoID , 
            BillingID , 
            PayID , 
            ReferralID , 
            SponsorID , 
            Sponsor2ID , 
            Sponsor3ID , 
            MentorID , 
            CompanyName , 
            NameLast , 
            NameFirst , 
            BV , 
            QV , 
            BV2 , 
            QV2 , 
            BV3 , 
            QV3 , 
            BV4 , 
            QV4 , 
            Qualify , 
            QualifyDate , 
            Email , 
            Email2 , 
            Phone1 , 
            Phone2 , 
            Fax , 
            Status , 
            Level , 
            Newsletter , 
            EnrollDate , 
            EndDate , 
            InitPrice , 
            Price , 
            Retail , 
            BusAccts , 
            BusAcctPrice , 
            BusAcctRetail , 
            IsDiscount , 
            Discount , 
            IsCompany , 
            Billing , 
            AccessLimit , 
            QuizLimit , 
            Reference , 
            Referral , 
            TrialDays , 
            MasterID , 
            IsIncluded , 
            IsMaster , 
            MasterPrice , 
            MasterMembers , 
            MaxMembers , 
            VisitDate , 
            TaxIDType , 
            TaxID , 
            AutoShipDate , 
            PaidDate , 
            StatusDate , 
            StatusChange , 
            LevelChange , 
            IsRemoved , 
            GroupID , 
            Role , 
            Secure , 
            Options , 
            Options2 , 
            Pos , 
            Signature , 
            SocNet , 
            ConfLine , 
            NotifyMentor , 
            Image , 
            Identification , 
            Title , 
            Title2 , 
            MinTitle , 
            TitleDate , 
            InputValues , 
            Icons , 
            IsMsg , 
            Timezone , 
            Process

            )
VALUES (
            @mAuthUserID ,
            @WebsiteID ,
            @CompanyID ,
            @PromoID ,
            @BillingID ,
            @PayID ,
            @ReferralID ,
            @SponsorID ,
            @Sponsor2ID ,
            @Sponsor3ID ,
            @MentorID ,
            @CompanyName ,
            @NameLast ,
            @NameFirst ,
            @BV ,
            @QV ,
            @BV2 ,
            @QV2 ,
            @BV3 ,
            @QV3 ,
            @BV4 ,
            @QV4 ,
            @Qualify ,
            @QualifyDate ,
            @Email ,
            @Email2 ,
            @Phone1 ,
            @Phone2 ,
            @Fax ,
            @Status ,
            @Level ,
            @Newsletter ,
            @EnrollDate ,
            @EndDate ,
            @InitPrice ,
            @Price ,
            @Retail ,
            @BusAccts ,
            @BusAcctPrice ,
            @BusAcctRetail ,
            @IsDiscount ,
            @Discount ,
            @IsCompany ,
            @Billing ,
            @AccessLimit ,
            @QuizLimit ,
            @Reference ,
            @Referral ,
            @TrialDays ,
            @MasterID ,
            @IsIncluded ,
            @IsMaster ,
            @MasterPrice ,
            @MasterMembers ,
            @MaxMembers ,
            @VisitDate ,
            @TaxIDType ,
            @TaxID ,
            @AutoShipDate ,
            @PaidDate ,
            @StatusDate ,
            @StatusChange ,
            @LevelChange ,
            @IsRemoved ,
            @GroupID ,
            @Role ,
            @Secure ,
            @Options ,
            @Options2 ,
            @Pos ,
            @Signature ,
            @SocNet ,
            @ConfLine ,
            @NotifyMentor ,
            @Image ,
            @Identification ,
            @Title ,
            @Title2 ,
            @MinTitle ,
            @TitleDate ,
            @InputValues ,
            @Icons ,
            @IsMsg ,
            @Timezone ,
            @Process
            )

SET @mNewID = @@Identity
SET @MemberID = @mNewID
SET @AuthUserID = @mAuthUserID
EXEC pts_Member_AddCustom
   @CompanyID ,
   @mNewID

GO