EXEC [dbo].pts_CheckProc 'pts_BarterAd_Update'
 GO

CREATE PROCEDURE [dbo].pts_BarterAd_Update ( 
   @BarterAdID int,
   @ConsumerID int,
   @BarterArea1ID int,
   @BarterArea2ID int,
   @BarterCategoryID int,
   @Title nvarchar (100),
   @Status int,
   @PostDate datetime,
   @UpdateDate datetime,
   @EndDate datetime,
   @Price money,
   @Location nvarchar (40),
   @Zip nvarchar (10),
   @Description nvarchar (4000),
   @Language nvarchar (10),
   @ContactName nvarchar (40),
   @ContactEmail nvarchar (80),
   @ContactPhone nvarchar (40),
   @IsEmail bit,
   @IsPhone bit,
   @IsText bit,
   @IsMore bit,
   @IsMap bit,
   @IsContact bit,
   @IsDealer bit,
   @MapStreet1 nvarchar (60),
   @MapStreet2 nvarchar (60),
   @MapCity nvarchar (30),
   @MapZip nvarchar (10),
   @Options varchar (20),
   @Payments varchar (20),
   @Condition int,
   @Images int,
   @GeoCode varchar (30),
   @T1 nvarchar (40),
   @T2 nvarchar (40),
   @T3 nvarchar (40),
   @T4 nvarchar (40),
   @T5 nvarchar (40),
   @N1 int,
   @N2 int,
   @N3 int,
   @N4 int,
   @N5 int,
   @L1 tinyint,
   @L2 tinyint,
   @L3 tinyint,
   @L4 tinyint,
   @L5 tinyint,
   @L6 tinyint,
   @L7 tinyint,
   @L8 tinyint,
   @L9 tinyint,
   @L10 tinyint,
   @Y1 bit,
   @Y2 bit,
   @Y3 bit,
   @Y4 bit,
   @Y5 bit,
   @Y6 bit,
   @Y7 bit,
   @Y8 bit,
   @Y9 bit,
   @Y10 bit,
   @D1 datetime,
   @D2 datetime,
   @D3 datetime,
   @D4 datetime,
   @D5 datetime,
   @UserID int
      )
AS

DECLARE @mNow datetime

SET NOCOUNT ON

SET @mNow = GETDATE()

UPDATE bad
SET bad.ConsumerID = @ConsumerID ,
   bad.BarterArea1ID = @BarterArea1ID ,
   bad.BarterArea2ID = @BarterArea2ID ,
   bad.BarterCategoryID = @BarterCategoryID ,
   bad.Title = @Title ,
   bad.Status = @Status ,
   bad.PostDate = @PostDate ,
   bad.UpdateDate = @UpdateDate ,
   bad.EndDate = @EndDate ,
   bad.Price = @Price ,
   bad.Location = @Location ,
   bad.Zip = @Zip ,
   bad.Description = @Description ,
   bad.Language = @Language ,
   bad.ContactName = @ContactName ,
   bad.ContactEmail = @ContactEmail ,
   bad.ContactPhone = @ContactPhone ,
   bad.IsEmail = @IsEmail ,
   bad.IsPhone = @IsPhone ,
   bad.IsText = @IsText ,
   bad.IsMore = @IsMore ,
   bad.IsMap = @IsMap ,
   bad.IsContact = @IsContact ,
   bad.IsDealer = @IsDealer ,
   bad.MapStreet1 = @MapStreet1 ,
   bad.MapStreet2 = @MapStreet2 ,
   bad.MapCity = @MapCity ,
   bad.MapZip = @MapZip ,
   bad.Options = @Options ,
   bad.Payments = @Payments ,
   bad.Condition = @Condition ,
   bad.Images = @Images ,
   bad.GeoCode = @GeoCode ,
   bad.T1 = @T1 ,
   bad.T2 = @T2 ,
   bad.T3 = @T3 ,
   bad.T4 = @T4 ,
   bad.T5 = @T5 ,
   bad.N1 = @N1 ,
   bad.N2 = @N2 ,
   bad.N3 = @N3 ,
   bad.N4 = @N4 ,
   bad.N5 = @N5 ,
   bad.L1 = @L1 ,
   bad.L2 = @L2 ,
   bad.L3 = @L3 ,
   bad.L4 = @L4 ,
   bad.L5 = @L5 ,
   bad.L6 = @L6 ,
   bad.L7 = @L7 ,
   bad.L8 = @L8 ,
   bad.L9 = @L9 ,
   bad.L10 = @L10 ,
   bad.Y1 = @Y1 ,
   bad.Y2 = @Y2 ,
   bad.Y3 = @Y3 ,
   bad.Y4 = @Y4 ,
   bad.Y5 = @Y5 ,
   bad.Y6 = @Y6 ,
   bad.Y7 = @Y7 ,
   bad.Y8 = @Y8 ,
   bad.Y9 = @Y9 ,
   bad.Y10 = @Y10 ,
   bad.D1 = @D1 ,
   bad.D2 = @D2 ,
   bad.D3 = @D3 ,
   bad.D4 = @D4 ,
   bad.D5 = @D5
FROM BarterAd AS bad
WHERE bad.BarterAdID = @BarterAdID

GO