EXEC [dbo].pts_CheckProc 'pts_Coption_Update'
 GO

CREATE PROCEDURE [dbo].pts_Coption_Update ( 
   @CoptionID int,
   @CompanyID int,
   @InitPrice money,
   @Price money,
   @Price2 money,
   @Price3 money,
   @Discount money,
   @Retail money,
   @Retail2 money,
   @Retail3 money,
   @BusPrice money,
   @BusRetail money,
   @BusAccts int,
   @BusAcctPrice money,
   @BusAcctRetail money,
   @IsCatalog bit,
   @IsDiscount bit,
   @Billing int,
   @CommRate money,
   @PromoCode int,
   @AccessLimit varchar (50),
   @QuizLimit int,
   @MemberLimit int,
   @TrialDays int,
   @IsTrialPayment bit,
   @IsSignIn bit,
   @IsJoinNow bit,
   @IsNewEmail bit,
   @IsBusAcct bit,
   @IsFree bit,
   @RefName nvarchar (20),
   @NewMemberOrgs varchar (20),
   @TBPage varchar (20),
   @Languages varchar (200),
   @UploadURL varchar (40),
   @SetupFee money,
   @IsSalesDefault bit,
   @ProjectsDefault int,
   @DocSizeLimit int,
   @FreeOptions varchar (40),
   @EasyOptions varchar (40),
   @Options varchar (50),
   @Options2 varchar (50),
   @Options3 varchar (50),
   @Options4 varchar (40),
   @Options5 varchar (40),
   @Options6 varchar (40),
   @Options7 varchar (40),
   @Options8 varchar (40),
   @FreeName nvarchar (40),
   @PaidName nvarchar (40),
   @PaidName2 nvarchar (40),
   @PaidName3 nvarchar (40),
   @Identify int,
   @Identification nvarchar (500),
   @MerchantCardType int,
   @MerchantCheckType int,
   @MerchantCardAcct nvarchar (100),
   @MerchantCheckAcct nvarchar (100),
   @WalletType varchar (20),
   @WalletAcct varchar (100),
   @PayoutProcessors varchar (20),
   @PaymentOptions varchar (15),
   @MiscPay1 nvarchar (30),
   @MiscPay2 nvarchar (30),
   @MiscPay3 nvarchar (30),
   @IPLimit int,
   @InputOptions nvarchar (1000),
   @GAAcct varchar (50),
   @Countries varchar (100),
   @MenuColors varchar (200),
   @Portal varchar (20),
   @Shopping varchar (20),
   @UserID int
      )
AS

DECLARE @mNow datetime

SET NOCOUNT ON

SET @mNow = GETDATE()

UPDATE cop
SET cop.CompanyID = @CompanyID ,
   cop.InitPrice = @InitPrice ,
   cop.Price = @Price ,
   cop.Price2 = @Price2 ,
   cop.Price3 = @Price3 ,
   cop.Discount = @Discount ,
   cop.Retail = @Retail ,
   cop.Retail2 = @Retail2 ,
   cop.Retail3 = @Retail3 ,
   cop.BusPrice = @BusPrice ,
   cop.BusRetail = @BusRetail ,
   cop.BusAccts = @BusAccts ,
   cop.BusAcctPrice = @BusAcctPrice ,
   cop.BusAcctRetail = @BusAcctRetail ,
   cop.IsCatalog = @IsCatalog ,
   cop.IsDiscount = @IsDiscount ,
   cop.Billing = @Billing ,
   cop.CommRate = @CommRate ,
   cop.PromoCode = @PromoCode ,
   cop.AccessLimit = @AccessLimit ,
   cop.QuizLimit = @QuizLimit ,
   cop.MemberLimit = @MemberLimit ,
   cop.TrialDays = @TrialDays ,
   cop.IsTrialPayment = @IsTrialPayment ,
   cop.IsSignIn = @IsSignIn ,
   cop.IsJoinNow = @IsJoinNow ,
   cop.IsNewEmail = @IsNewEmail ,
   cop.IsBusAcct = @IsBusAcct ,
   cop.IsFree = @IsFree ,
   cop.RefName = @RefName ,
   cop.NewMemberOrgs = @NewMemberOrgs ,
   cop.TBPage = @TBPage ,
   cop.Languages = @Languages ,
   cop.UploadURL = @UploadURL ,
   cop.SetupFee = @SetupFee ,
   cop.IsSalesDefault = @IsSalesDefault ,
   cop.ProjectsDefault = @ProjectsDefault ,
   cop.DocSizeLimit = @DocSizeLimit ,
   cop.FreeOptions = @FreeOptions ,
   cop.EasyOptions = @EasyOptions ,
   cop.Options = @Options ,
   cop.Options2 = @Options2 ,
   cop.Options3 = @Options3 ,
   cop.Options4 = @Options4 ,
   cop.Options5 = @Options5 ,
   cop.Options6 = @Options6 ,
   cop.Options7 = @Options7 ,
   cop.Options8 = @Options8 ,
   cop.FreeName = @FreeName ,
   cop.PaidName = @PaidName ,
   cop.PaidName2 = @PaidName2 ,
   cop.PaidName3 = @PaidName3 ,
   cop.Identify = @Identify ,
   cop.Identification = @Identification ,
   cop.MerchantCardType = @MerchantCardType ,
   cop.MerchantCheckType = @MerchantCheckType ,
   cop.MerchantCardAcct = @MerchantCardAcct ,
   cop.MerchantCheckAcct = @MerchantCheckAcct ,
   cop.WalletType = @WalletType ,
   cop.WalletAcct = @WalletAcct ,
   cop.PayoutProcessors = @PayoutProcessors ,
   cop.PaymentOptions = @PaymentOptions ,
   cop.MiscPay1 = @MiscPay1 ,
   cop.MiscPay2 = @MiscPay2 ,
   cop.MiscPay3 = @MiscPay3 ,
   cop.IPLimit = @IPLimit ,
   cop.InputOptions = @InputOptions ,
   cop.GAAcct = @GAAcct ,
   cop.Countries = @Countries ,
   cop.MenuColors = @MenuColors ,
   cop.Portal = @Portal ,
   cop.Shopping = @Shopping
FROM Coption AS cop
WHERE cop.CoptionID = @CoptionID

GO