EXEC [dbo].pts_CheckProc 'pts_Profile_Add'
 GO

CREATE PROCEDURE [dbo].pts_Profile_Add ( 
   @ProfileID int OUTPUT,
   @MemberID int,
   @ProfileDate datetime,
   @ProfileType int,
   @Status int,
   @VQResponse nvarchar (50),
   @SQResponse nvarchar (50),
   @VQDiff int,
   @VQDimPerc int,
   @VQDimPos_I int,
   @VQDimPos_E int,
   @VQDimPos_S int,
   @VQDimNeg_I int,
   @VQDimNeg_E int,
   @VQDimNeg_S int,
   @VQIntCate_I int,
   @VQIntCate_E int,
   @VQIntCate_S int,
   @VQInt int,
   @VQIntPerc int,
   @VQDI int,
   @VQDIS int,
   @VQLeft int,
   @VQRight int,
   @VQAI int,
   @SQDiff int,
   @SQDimPerc int,
   @SQDimPos_I int,
   @SQDimPos_E int,
   @SQDimPos_S int,
   @SQDimNeg_I int,
   @SQDimNeg_E int,
   @SQDimNeg_S int,
   @SQIntCate_I int,
   @SQIntCate_E int,
   @SQIntCate_S int,
   @SQInt int,
   @SQIntPerc int,
   @SQDI int,
   @SQDIS int,
   @SQLeft int,
   @SQRight int,
   @SQAI int,
   @BQrLeft money,
   @BQrRight money,
   @BQaLeft int,
   @BQaRight int,
   @CQLeft int,
   @CQRight int,
   @RQLeft money,
   @RQRight money,
   @VQClarity_I int,
   @VQClarity_E int,
   @VQClarity_S int,
   @VQBias_I int,
   @VQBias_E int,
   @VQBias_S int,
   @SQClarity_I int,
   @SQClarity_E int,
   @SQClarity_S int,
   @SQBias_I int,
   @SQBias_E int,
   @SQBias_S int,
   @xVQClarity_I int,
   @xVQClarity_E int,
   @xVQClarity_S int,
   @xVQBias_I money,
   @xVQBias_E money,
   @xVQBias_S money,
   @xSQClarity_I int,
   @xSQClarity_E int,
   @xSQClarity_S int,
   @xSQBias_I money,
   @xSQBias_E money,
   @xSQBias_S money,
   @UserID int
      )
AS

DECLARE @mNow datetime
DECLARE @mNewID int

SET NOCOUNT ON

SET @mNow = GETDATE()


INSERT INTO Profile (
            MemberID , 
            ProfileDate , 
            ProfileType , 
            Status , 
            VQResponse , 
            SQResponse , 
            VQDiff , 
            VQDimPerc , 
            VQDimPos_I , 
            VQDimPos_E , 
            VQDimPos_S , 
            VQDimNeg_I , 
            VQDimNeg_E , 
            VQDimNeg_S , 
            VQIntCate_I , 
            VQIntCate_E , 
            VQIntCate_S , 
            VQInt , 
            VQIntPerc , 
            VQDI , 
            VQDIS , 
            VQLeft , 
            VQRight , 
            VQAI , 
            SQDiff , 
            SQDimPerc , 
            SQDimPos_I , 
            SQDimPos_E , 
            SQDimPos_S , 
            SQDimNeg_I , 
            SQDimNeg_E , 
            SQDimNeg_S , 
            SQIntCate_I , 
            SQIntCate_E , 
            SQIntCate_S , 
            SQInt , 
            SQIntPerc , 
            SQDI , 
            SQDIS , 
            SQLeft , 
            SQRight , 
            SQAI , 
            BQrLeft , 
            BQrRight , 
            BQaLeft , 
            BQaRight , 
            CQLeft , 
            CQRight , 
            RQLeft , 
            RQRight , 
            VQClarity_I , 
            VQClarity_E , 
            VQClarity_S , 
            VQBias_I , 
            VQBias_E , 
            VQBias_S , 
            SQClarity_I , 
            SQClarity_E , 
            SQClarity_S , 
            SQBias_I , 
            SQBias_E , 
            SQBias_S , 
            xVQClarity_I , 
            xVQClarity_E , 
            xVQClarity_S , 
            xVQBias_I , 
            xVQBias_E , 
            xVQBias_S , 
            xSQClarity_I , 
            xSQClarity_E , 
            xSQClarity_S , 
            xSQBias_I , 
            xSQBias_E , 
            xSQBias_S
            )
VALUES (
            @MemberID ,
            @ProfileDate ,
            @ProfileType ,
            @Status ,
            @VQResponse ,
            @SQResponse ,
            @VQDiff ,
            @VQDimPerc ,
            @VQDimPos_I ,
            @VQDimPos_E ,
            @VQDimPos_S ,
            @VQDimNeg_I ,
            @VQDimNeg_E ,
            @VQDimNeg_S ,
            @VQIntCate_I ,
            @VQIntCate_E ,
            @VQIntCate_S ,
            @VQInt ,
            @VQIntPerc ,
            @VQDI ,
            @VQDIS ,
            @VQLeft ,
            @VQRight ,
            @VQAI ,
            @SQDiff ,
            @SQDimPerc ,
            @SQDimPos_I ,
            @SQDimPos_E ,
            @SQDimPos_S ,
            @SQDimNeg_I ,
            @SQDimNeg_E ,
            @SQDimNeg_S ,
            @SQIntCate_I ,
            @SQIntCate_E ,
            @SQIntCate_S ,
            @SQInt ,
            @SQIntPerc ,
            @SQDI ,
            @SQDIS ,
            @SQLeft ,
            @SQRight ,
            @SQAI ,
            @BQrLeft ,
            @BQrRight ,
            @BQaLeft ,
            @BQaRight ,
            @CQLeft ,
            @CQRight ,
            @RQLeft ,
            @RQRight ,
            @VQClarity_I ,
            @VQClarity_E ,
            @VQClarity_S ,
            @VQBias_I ,
            @VQBias_E ,
            @VQBias_S ,
            @SQClarity_I ,
            @SQClarity_E ,
            @SQClarity_S ,
            @SQBias_I ,
            @SQBias_E ,
            @SQBias_S ,
            @xVQClarity_I ,
            @xVQClarity_E ,
            @xVQClarity_S ,
            @xVQBias_I ,
            @xVQBias_E ,
            @xVQBias_S ,
            @xSQClarity_I ,
            @xSQClarity_E ,
            @xSQClarity_S ,
            @xSQBias_I ,
            @xSQBias_E ,
            @xSQBias_S            )

SET @mNewID = @@IDENTITY

SET @ProfileID = @mNewID

GO