MD c:\pts\LIB
MD c:\pts\WEB
MD c:\pts\WEB\Attachments
MD c:\pts\WEB\Attachments\4
MD c:\pts\WEB\Attachments\23
MD c:\pts\WEB\Attachments\28
MD c:\pts\WEB\Attachments\38
MD c:\pts\WEB\Attachments\64
MD c:\pts\WEB\Attachments\75
MD c:\pts\WEB\Attachments\81
MD c:\pts\WEB\Attachments\-81
MD c:\pts\WEB\Billing
MD c:\pts\WEB\CKEditor
MD c:\pts\WEB\Drip
MD c:\pts\WEB\Export
MD c:\pts\WEB\Export\Assessment
MD c:\pts\WEB\Export\Course
MD c:\pts\WEB\Export\Metrics
MD c:\pts\WEB\Export\Page
MD c:\pts\WEB\Images
MD c:\pts\WEB\Images\Ad
MD c:\pts\WEB\Images\Affiliate
MD c:\pts\WEB\Images\Charts
MD c:\pts\WEB\Images\Company
MD c:\pts\WEB\Images\LeadCampaign
MD c:\pts\WEB\Images\Member
MD c:\pts\WEB\Images\News
MD c:\pts\WEB\Images\Page
MD c:\pts\WEB\Images\Support
MD c:\pts\WEB\Images\Trainer
MD c:\pts\WEB\Imagesb
MD c:\pts\WEB\img
MD c:\pts\WEB\Import
MD c:\pts\WEB\Include
MD c:\pts\WEB\Language
MD c:\pts\WEB\Library
MD c:\pts\WEB\Log
MD c:\pts\WEB\News
MD c:\pts\WEB\Orders
MD c:\pts\WEB\P-Images
MD c:\pts\WEB\Pages
MD c:\pts\WEB\Payout
MD c:\pts\WEB\Sections
MD c:\pts\WEB\Sections\Assessment
MD c:\pts\WEB\Sections\Billing
MD c:\pts\WEB\Sections\Company
MD c:\pts\WEB\Sections\Course
MD c:\pts\WEB\Sections\Money
MD c:\pts\WEB\Sections\News
MD c:\pts\WEB\Sections\Promotion
MD c:\pts\WEB\Sections\SalesCampaign
MD c:\pts\WEB\Sections\Trainer
