--SET IDENTITY_INSERT to ON.
SET IDENTITY_INSERT Country ON

INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 1, 'Andorra', 'AD', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 2, 'United Arab Emirates', 'AE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 3, 'Afghanistan', 'AF', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 4, 'Antigua And Barbuda', 'AG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 5, 'Anguilla', 'AI', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 6, 'Albania', 'AL', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 7, 'Armenia', 'AM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 8, 'Netherlands Antilles', 'AN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 9, 'Angola', 'AO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 10, 'Antarctica', 'AQ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 11, 'Argentina', 'AR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 12, 'American Samoa', 'AS', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 13, 'Austria', 'AT', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 14, 'Australia', 'AU', 6 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 15, 'Aruba', 'AW', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 16, 'Land Islands', 'AX', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 17, 'Azerbaijan', 'AZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 18, 'Bosnia And Herzegovina', 'BA', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 19, 'Barbados', 'BB', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 20, 'Bangladesh', 'BD', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 21, 'Belgium', 'BE', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 22, 'Burkina Faso', 'BF', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 23, 'Bulgaria', 'BG', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 24, 'Bahrain', 'BH', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 25, 'Burundi', 'BI', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 26, 'Benin', 'BJ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 27, 'Bermuda', 'BM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 28, 'Brunei Darussalam', 'BN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 29, 'Bolivia', 'BO', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 30, 'Brazil', 'BR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 31, 'Bahamas', 'BS', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 32, 'Bhutan', 'BT', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 33, 'Bouvet Island', 'BV', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 34, 'Botswana', 'BW', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 35, 'Belarus', 'BY', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 36, 'Belize', 'BZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 37, 'Canada', 'CA', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 38, 'Cocos (Keeling) Islands', 'CC', 6 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 39, 'Congo, The Democratic Republic Of The', 'CD', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 40, 'Central African Republic', 'CF', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 41, 'Congo', 'CG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 42, 'Switzerland', 'CH', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 43, 'Cte Divoire', 'CI', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 44, 'Cook Islands', 'CK', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 45, 'Chile', 'CL', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 46, 'Cameroon', 'CM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 47, 'China', 'CN', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 48, 'Colombia', 'CO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 49, 'Costa Rica', 'CR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 50, 'Serbia And Montenegro', 'CS', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 51, 'Cuba', 'CU', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 52, 'Cape Verde', 'CV', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 53, 'Christmas Island', 'CX', 6 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 54, 'Cyprus', 'CY', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 55, 'Czech Republic', 'CZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 56, 'Germany', 'DE', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 57, 'Djibouti', 'DJ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 58, 'Denmark', 'DK', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 59, 'Dominica', 'DM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 60, 'Dominican Republic', 'DO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 61, 'Algeria', 'DZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 62, 'Ecuador', 'EC', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 63, 'Estonia', 'EE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 64, 'Egypt', 'EG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 65, 'Western Sahara', 'EH', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 66, 'Eritrea', 'ER', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 67, 'Spain', 'ES', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 68, 'Ethiopia', 'ET', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 69, 'Finland', 'FI', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 70, 'Fiji', 'FJ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 71, 'Falkland Islands (Malvinas)', 'FK', 7 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 72, 'Micronesia, Federated States Of', 'FM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 73, 'Faroe Islands', 'FO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 74, 'France', 'FR', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 75, 'Gabon', 'GA', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 76, 'United Kingdom', 'GB', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 77, 'Grenada', 'GD', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 78, 'Georgia', 'GE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 79, 'French Guiana', 'GF', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 80, 'Ghana', 'GH', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 81, 'Gibraltar', 'GI', 7 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 82, 'Greenland', 'GL', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 83, 'Gambia', 'GM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 84, 'Guinea', 'GN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 85, 'Guadeloupe', 'GP', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 86, 'Equatorial Guinea', 'GQ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 87, 'Greece', 'GR', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 88, 'South Georgia And The South Sandwich Islands', 'GS', 7 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 89, 'Guatemala', 'GT', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 90, 'Guam', 'GU', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 91, 'Guinea-Bissau', 'GW', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 92, 'Guyana', 'GY', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 93, 'Hong Kong', 'HK', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 94, 'Heard Island And Mcdonald Islands', 'HM', 6 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 95, 'Honduras', 'HN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 96, 'Croatia', 'HR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 97, 'Haiti', 'HT', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 98, 'Hungary', 'HU', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 99, 'Indonesia', 'ID', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 100, 'Ireland', 'IE', 7 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 101, 'Israel', 'IL', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 102, 'India', 'IN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 103, 'British Indian Ocean Territory', 'IO', 7 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 104, 'Iraq', 'IQ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 105, 'Iran, Islamic Republic Of', 'IR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 106, 'Iceland', 'IS', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 107, 'Italy', 'IT', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 108, 'Jamaica', 'JM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 109, 'Jordan', 'JO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 110, 'Japan', 'JP', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 111, 'Kenya', 'KE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 112, 'Kyrgyzstan', 'KG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 113, 'Cambodia', 'KH', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 114, 'Kiribati', 'KI', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 115, 'Comoros', 'KM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 116, 'Saint Kitts And Nevis', 'KN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 117, 'Korea, Democratic Peoples Republic Of', 'KP', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 118, 'Korea, Republic Of', 'KR', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 119, 'Kuwait', 'KW', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 120, 'Cayman Islands', 'KY', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 121, 'Kazakhstan', 'KZ', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 122, 'Lao Peoples Democratic Republic', 'LA', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 123, 'Lebanon', 'LB', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 124, 'Saint Lucia', 'LC', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 125, 'Liechtenstein', 'LI', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 126, 'Sri Lanka', 'LK', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 127, 'Liberia', 'LR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 128, 'Lesotho', 'LS', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 129, 'Lithuania', 'LT', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 130, 'Luxembourg', 'LU', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 131, 'Latvia', 'LV', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 132, 'Libyan Arab Jamahiriya', 'LY', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 133, 'Morocco', 'MA', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 134, 'Monaco', 'MC', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 135, 'Moldova, Republic Of', 'MD', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 136, 'Madagascar', 'MG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 137, 'Marshall Islands', 'MH', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 138, 'Macedonia, The Former Yugoslav Republic Of', 'MK', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 139, 'Mali', 'ML', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 140, 'Myanmar', 'MM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 141, 'Mongolia', 'MN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 142, 'Macao', 'MO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 143, 'Northern Mariana Islands', 'MP', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 144, 'Martinique', 'MQ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 145, 'Mauritania', 'MR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 146, 'Montserrat', 'MS', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 147, 'Malta', 'MT', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 148, 'Mauritius', 'MU', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 149, 'Maldives', 'MV', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 150, 'Malawi', 'MW', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 151, 'Mexico', 'MX', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 152, 'Malaysia', 'MY', 2 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 153, 'Mozambique', 'MZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 154, 'Namibia', 'NA', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 155, 'New Caledonia', 'NC', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 156, 'Niger', 'NE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 157, 'Norfolk Island', 'NF', 6 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 158, 'Nigeria', 'NG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 159, 'Nicaragua', 'NI', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 160, 'Netherlands', 'NL', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 161, 'Norway', 'NO', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 162, 'Nepal', 'NP', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 163, 'Nauru', 'NR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 164, 'Niue', 'NU', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 165, 'New Zealand', 'NZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 166, 'Oman', 'OM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 167, 'Panama', 'PA', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 168, 'Peru', 'PE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 169, 'French Polynesia', 'PF', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 170, 'Papua New Guinea', 'PG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 171, 'Philippines', 'PH', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 172, 'Pakistan', 'PK', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 173, 'Poland', 'PL', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 174, 'Saint Pierre And Miquelon', 'PM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 175, 'Pitcairn', 'PN', 7 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 176, 'Puerto Rico', 'PR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 177, 'Palestinian Territory, Occupied', 'PS', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 178, 'Portugal', 'PT', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 179, 'Palau', 'PW', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 180, 'Paraguay', 'PY', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 181, 'Qatar', 'QA', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 182, 'Runion', 'RE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 183, 'Romania', 'RO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 184, 'Russian Federation', 'RU', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 185, 'Rwanda', 'RW', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 186, 'Saudi Arabia', 'SA', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 187, 'Solomon Islands', 'SB', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 188, 'Seychelles', 'SC', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 189, 'Sudan', 'SD', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 190, 'Sweden', 'SE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 191, 'Singapore', 'SG', 3 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 192, 'Saint Helena', 'SH', 7 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 193, 'Slovenia', 'SI', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 194, 'Svalbard And Jan Mayen', 'SJ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 195, 'Slovakia', 'SK', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 196, 'Sierra Leone', 'SL', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 197, 'San Marino', 'SM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 198, 'Senegal', 'SN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 199, 'Somalia', 'SO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 200, 'Suriname', 'SR', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 201, 'Sao Tome And Principe', 'ST', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 202, 'El Salvador', 'SV', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 203, 'Syrian Arab Republic', 'SY', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 204, 'Swaziland', 'SZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 205, 'Turks And Caicos Islands', 'TC', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 206, 'Chad', 'TD', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 207, 'French Southern Territories', 'TF', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 208, 'Togo', 'TG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 209, 'Thailand', 'TH', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 210, 'Tajikistan', 'TJ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 211, 'Tokelau', 'TK', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 212, 'Timor-Leste', 'TL', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 213, 'Turkmenistan', 'TM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 214, 'Tunisia', 'TN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 215, 'Tonga', 'TO', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 216, 'Turkey', 'TR', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 217, 'Trinidad And Tobago', 'TT', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 218, 'Tuvalu', 'TV', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 219, 'Taiwan', 'TW', 5 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 220, 'Tanzania, United Republic Of', 'TZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 221, 'Ukraine', 'UA', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 222, 'Uganda', 'UG', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 223, 'United States Minor Outlying Islands', 'UM', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 224, 'United States', 'US', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 225, 'Uruguay', 'UY', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 226, 'Uzbekistan', 'UZ', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 227, 'Holy See (Vatican City State)', 'VA', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 228, 'Saint Vincent And The Grenadines', 'VC', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 229, 'Venezuela', 'VE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 230, 'Virgin Islands, U.S.', 'VI', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 231, 'Viet Nam', 'VN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 232, 'Vanuatu', 'VU', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 233, 'Wallis And Futuna', 'WF', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 234, 'Samoa', 'WS', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 235, 'Yemen', 'YE', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 236, 'Mayotte', 'YT', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 237, 'South Africa', 'ZA', 1 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 238, 'Zambia', 'ZM', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 239, 'Zimbabwe', 'ZW', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 240, 'Saint Maarten', 'AN', 0 )
INSERT INTO Country (CountryID, CountryName, Code, Curr ) VALUES ( 241, 'Saint Martin', 'MF', 0 )

SET IDENTITY_INSERT Country OFF
