<%
Function LanguageCode(byval bvCode)
On Error Resume Next
LanguageCode="English"
Select Case bvCode
Case "en": LanguageCode="English"
Case "af": LanguageCode="Afrikaans"
Case "sq": LanguageCode="Albanian"
Case "ar": LanguageCode="Arabic"
Case "hy": LanguageCode="Armenian"
Case "eu": LanguageCode="Basque"
Case "be": LanguageCode="Belarusian"
Case "bn": LanguageCode="Bengali"
Case "bs": LanguageCode="Bosnian"
Case "bg": LanguageCode="Bulgarian"
Case "ca": LanguageCode="Catalan"
Case "ce": LanguageCode="Chechen"
Case "zh": LanguageCode="Chinese"
Case "co": LanguageCode="Croatian"
Case "cs": LanguageCode="Czech"
Case "da": LanguageCode="Danish"
Case "nl": LanguageCode="Dutch"
Case "et": LanguageCode="Estonia"
Case "fo": LanguageCode="Faroese"
Case "fil": LanguageCode="Filipino"
Case "fi": LanguageCode="Finnish"
Case "fr": LanguageCode="French"
Case "de": LanguageCode="German"
Case "he": LanguageCode="Hebrew"
Case "hi": LanguageCode="Hindi"
Case "hu": LanguageCode="Hungarian"
Case "ga": LanguageCode="Irish"
Case "is": LanguageCode="Icelandic"
Case "it": LanguageCode="Italian"
Case "ja": LanguageCode="Japanese"
Case "ko": LanguageCode="Korean"
Case "mt": LanguageCode="Maltese"
Case "mn": LanguageCode="Mongolian"
Case "no": LanguageCode="Norwegian"
Case "pt": LanguageCode="Portuguese"
Case "ru": LanguageCode="Russian"
Case "sr": LanguageCode="Serbian"
Case "es": LanguageCode="Spanish"
Case "sv": LanguageCode="Swedish"
Case "th": LanguageCode="Thai"
Case "tr": LanguageCode="Turkish"
Case "vi": LanguageCode="Vietnamese"
End Select
End Function
%>

