EXEC [dbo].pts_CheckTable 'BarterAd'
 GO

CREATE TABLE [dbo].[BarterAd] (
   [BarterAdID] int IDENTITY (1,1) NOT NULL ,
   [ConsumerID] int NOT NULL ,
   [BarterArea1ID] int NOT NULL ,
   [BarterArea2ID] int NOT NULL ,
   [BarterCategoryID] int NOT NULL ,
   [Title] nvarchar (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Status] int NOT NULL ,
   [PostDate] datetime NOT NULL ,
   [UpdateDate] datetime NOT NULL ,
   [EndDate] datetime NOT NULL ,
   [Price] money NOT NULL ,
   [Location] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Zip] nvarchar (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Description] nvarchar (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Language] nvarchar (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [ContactName] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [ContactEmail] nvarchar (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [ContactPhone] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [IsEmail] bit NOT NULL ,
   [IsPhone] bit NOT NULL ,
   [IsText] bit NOT NULL ,
   [IsMore] bit NOT NULL ,
   [IsMap] bit NOT NULL ,
   [IsContact] bit NOT NULL ,
   [IsDealer] bit NOT NULL ,
   [MapStreet1] nvarchar (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MapStreet2] nvarchar (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MapCity] nvarchar (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MapZip] nvarchar (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options] varchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Payments] varchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Condition] int NOT NULL ,
   [Images] int NOT NULL ,
   [GeoCode] varchar (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [T1] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [T2] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [T3] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [T4] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [T5] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [N1] int NOT NULL ,
   [N2] int NOT NULL ,
   [N3] int NOT NULL ,
   [N4] int NOT NULL ,
   [N5] int NOT NULL ,
   [L1] tinyint NOT NULL ,
   [L2] tinyint NOT NULL ,
   [L3] tinyint NOT NULL ,
   [L4] tinyint NOT NULL ,
   [L5] tinyint NOT NULL ,
   [L6] tinyint NOT NULL ,
   [L7] tinyint NOT NULL ,
   [L8] tinyint NOT NULL ,
   [L9] tinyint NOT NULL ,
   [L10] tinyint NOT NULL ,
   [Y1] bit NOT NULL ,
   [Y2] bit NOT NULL ,
   [Y3] bit NOT NULL ,
   [Y4] bit NOT NULL ,
   [Y5] bit NOT NULL ,
   [Y6] bit NOT NULL ,
   [Y7] bit NOT NULL ,
   [Y8] bit NOT NULL ,
   [Y9] bit NOT NULL ,
   [Y10] bit NOT NULL ,
   [D1] datetime NOT NULL ,
   [D2] datetime NOT NULL ,
   [D3] datetime NOT NULL ,
   [D4] datetime NOT NULL ,
   [D5] datetime NOT NULL 
   ) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BarterAd] WITH NOCHECK ADD
   CONSTRAINT [DF_BarterAd_ConsumerID] DEFAULT (0) FOR [ConsumerID] ,
   CONSTRAINT [DF_BarterAd_BarterArea1ID] DEFAULT (0) FOR [BarterArea1ID] ,
   CONSTRAINT [DF_BarterAd_BarterArea2ID] DEFAULT (0) FOR [BarterArea2ID] ,
   CONSTRAINT [DF_BarterAd_BarterCategoryID] DEFAULT (0) FOR [BarterCategoryID] ,
   CONSTRAINT [DF_BarterAd_Title] DEFAULT ('') FOR [Title] ,
   CONSTRAINT [DF_BarterAd_Status] DEFAULT (0) FOR [Status] ,
   CONSTRAINT [DF_BarterAd_PostDate] DEFAULT (0) FOR [PostDate] ,
   CONSTRAINT [DF_BarterAd_UpdateDate] DEFAULT (0) FOR [UpdateDate] ,
   CONSTRAINT [DF_BarterAd_EndDate] DEFAULT (0) FOR [EndDate] ,
   CONSTRAINT [DF_BarterAd_Price] DEFAULT (0) FOR [Price] ,
   CONSTRAINT [DF_BarterAd_Location] DEFAULT ('') FOR [Location] ,
   CONSTRAINT [DF_BarterAd_Zip] DEFAULT ('') FOR [Zip] ,
   CONSTRAINT [DF_BarterAd_Description] DEFAULT ('') FOR [Description] ,
   CONSTRAINT [DF_BarterAd_Language] DEFAULT ('') FOR [Language] ,
   CONSTRAINT [DF_BarterAd_ContactName] DEFAULT ('') FOR [ContactName] ,
   CONSTRAINT [DF_BarterAd_ContactEmail] DEFAULT ('') FOR [ContactEmail] ,
   CONSTRAINT [DF_BarterAd_ContactPhone] DEFAULT ('') FOR [ContactPhone] ,
   CONSTRAINT [DF_BarterAd_IsEmail] DEFAULT (0) FOR [IsEmail] ,
   CONSTRAINT [DF_BarterAd_IsPhone] DEFAULT (0) FOR [IsPhone] ,
   CONSTRAINT [DF_BarterAd_IsText] DEFAULT (0) FOR [IsText] ,
   CONSTRAINT [DF_BarterAd_IsMore] DEFAULT (0) FOR [IsMore] ,
   CONSTRAINT [DF_BarterAd_IsMap] DEFAULT (0) FOR [IsMap] ,
   CONSTRAINT [DF_BarterAd_IsContact] DEFAULT (0) FOR [IsContact] ,
   CONSTRAINT [DF_BarterAd_IsDealer] DEFAULT (0) FOR [IsDealer] ,
   CONSTRAINT [DF_BarterAd_MapStreet1] DEFAULT ('') FOR [MapStreet1] ,
   CONSTRAINT [DF_BarterAd_MapStreet2] DEFAULT ('') FOR [MapStreet2] ,
   CONSTRAINT [DF_BarterAd_MapCity] DEFAULT ('') FOR [MapCity] ,
   CONSTRAINT [DF_BarterAd_MapZip] DEFAULT ('') FOR [MapZip] ,
   CONSTRAINT [DF_BarterAd_Options] DEFAULT ('') FOR [Options] ,
   CONSTRAINT [DF_BarterAd_Payments] DEFAULT ('') FOR [Payments] ,
   CONSTRAINT [DF_BarterAd_Condition] DEFAULT (0) FOR [Condition] ,
   CONSTRAINT [DF_BarterAd_Images] DEFAULT (0) FOR [Images] ,
   CONSTRAINT [DF_BarterAd_GeoCode] DEFAULT ('') FOR [GeoCode] ,
   CONSTRAINT [DF_BarterAd_T1] DEFAULT ('') FOR [T1] ,
   CONSTRAINT [DF_BarterAd_T2] DEFAULT ('') FOR [T2] ,
   CONSTRAINT [DF_BarterAd_T3] DEFAULT ('') FOR [T3] ,
   CONSTRAINT [DF_BarterAd_T4] DEFAULT ('') FOR [T4] ,
   CONSTRAINT [DF_BarterAd_T5] DEFAULT ('') FOR [T5] ,
   CONSTRAINT [DF_BarterAd_N1] DEFAULT (0) FOR [N1] ,
   CONSTRAINT [DF_BarterAd_N2] DEFAULT (0) FOR [N2] ,
   CONSTRAINT [DF_BarterAd_N3] DEFAULT (0) FOR [N3] ,
   CONSTRAINT [DF_BarterAd_N4] DEFAULT (0) FOR [N4] ,
   CONSTRAINT [DF_BarterAd_N5] DEFAULT (0) FOR [N5] ,
   CONSTRAINT [DF_BarterAd_L1] DEFAULT (0) FOR [L1] ,
   CONSTRAINT [DF_BarterAd_L2] DEFAULT (0) FOR [L2] ,
   CONSTRAINT [DF_BarterAd_L3] DEFAULT (0) FOR [L3] ,
   CONSTRAINT [DF_BarterAd_L4] DEFAULT (0) FOR [L4] ,
   CONSTRAINT [DF_BarterAd_L5] DEFAULT (0) FOR [L5] ,
   CONSTRAINT [DF_BarterAd_L6] DEFAULT (0) FOR [L6] ,
   CONSTRAINT [DF_BarterAd_L7] DEFAULT (0) FOR [L7] ,
   CONSTRAINT [DF_BarterAd_L8] DEFAULT (0) FOR [L8] ,
   CONSTRAINT [DF_BarterAd_L9] DEFAULT (0) FOR [L9] ,
   CONSTRAINT [DF_BarterAd_L10] DEFAULT (0) FOR [L10] ,
   CONSTRAINT [DF_BarterAd_Y1] DEFAULT (0) FOR [Y1] ,
   CONSTRAINT [DF_BarterAd_Y2] DEFAULT (0) FOR [Y2] ,
   CONSTRAINT [DF_BarterAd_Y3] DEFAULT (0) FOR [Y3] ,
   CONSTRAINT [DF_BarterAd_Y4] DEFAULT (0) FOR [Y4] ,
   CONSTRAINT [DF_BarterAd_Y5] DEFAULT (0) FOR [Y5] ,
   CONSTRAINT [DF_BarterAd_Y6] DEFAULT (0) FOR [Y6] ,
   CONSTRAINT [DF_BarterAd_Y7] DEFAULT (0) FOR [Y7] ,
   CONSTRAINT [DF_BarterAd_Y8] DEFAULT (0) FOR [Y8] ,
   CONSTRAINT [DF_BarterAd_Y9] DEFAULT (0) FOR [Y9] ,
   CONSTRAINT [DF_BarterAd_Y10] DEFAULT (0) FOR [Y10] ,
   CONSTRAINT [DF_BarterAd_D1] DEFAULT (0) FOR [D1] ,
   CONSTRAINT [DF_BarterAd_D2] DEFAULT (0) FOR [D2] ,
   CONSTRAINT [DF_BarterAd_D3] DEFAULT (0) FOR [D3] ,
   CONSTRAINT [DF_BarterAd_D4] DEFAULT (0) FOR [D4] ,
   CONSTRAINT [DF_BarterAd_D5] DEFAULT (0) FOR [D5]
GO

ALTER TABLE [dbo].[BarterAd] WITH NOCHECK ADD
   CONSTRAINT [PK_BarterAd] PRIMARY KEY NONCLUSTERED
   ([BarterAdID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO

CREATE INDEX [I_BarterAd_BarterArea1ID]
   ON [dbo].[BarterAd]
   ([BarterArea1ID], [BarterCategoryID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO