EXEC [dbo].pts_CheckTable 'Coption'
 GO

CREATE TABLE [dbo].[Coption] (
   [CoptionID] int IDENTITY (1,1) NOT NULL ,
   [CompanyID] int NOT NULL ,
   [InitPrice] money NOT NULL ,
   [Price] money NOT NULL ,
   [Price2] money NOT NULL ,
   [Price3] money NOT NULL ,
   [Discount] money NOT NULL ,
   [Retail] money NOT NULL ,
   [Retail2] money NOT NULL ,
   [Retail3] money NOT NULL ,
   [BusPrice] money NOT NULL ,
   [BusRetail] money NOT NULL ,
   [BusAccts] int NOT NULL ,
   [BusAcctPrice] money NOT NULL ,
   [BusAcctRetail] money NOT NULL ,
   [IsCatalog] bit NOT NULL ,
   [IsDiscount] bit NOT NULL ,
   [Billing] int NOT NULL ,
   [CommRate] money NOT NULL ,
   [PromoCode] int NOT NULL ,
   [AccessLimit] varchar (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [QuizLimit] int NOT NULL ,
   [MemberLimit] int NOT NULL ,
   [TrialDays] int NOT NULL ,
   [IsTrialPayment] bit NOT NULL ,
   [IsSignIn] bit NOT NULL ,
   [IsJoinNow] bit NOT NULL ,
   [IsNewEmail] bit NOT NULL ,
   [IsBusAcct] bit NOT NULL ,
   [IsFree] bit NOT NULL ,
   [RefName] nvarchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [NewMemberOrgs] varchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [TBPage] varchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Languages] varchar (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [UploadURL] varchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [SetupFee] money NOT NULL ,
   [IsSalesDefault] bit NOT NULL ,
   [ProjectsDefault] int NOT NULL ,
   [DocSizeLimit] int NOT NULL ,
   [FreeOptions] varchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [EasyOptions] varchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options] varchar (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options2] varchar (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options3] varchar (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options4] varchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options5] varchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options6] varchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options7] varchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Options8] varchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [FreeName] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [PaidName] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [PaidName2] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [PaidName3] nvarchar (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Identify] int NOT NULL ,
   [Identification] nvarchar (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MerchantCardType] int NOT NULL ,
   [MerchantCheckType] int NOT NULL ,
   [MerchantCardAcct] nvarchar (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MerchantCheckAcct] nvarchar (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [WalletType] varchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [WalletAcct] varchar (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [PayoutProcessors] varchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [PaymentOptions] varchar (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MiscPay1] nvarchar (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MiscPay2] nvarchar (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MiscPay3] nvarchar (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [IPLimit] int NOT NULL ,
   [InputOptions] nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [GAAcct] varchar (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Countries] varchar (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [MenuColors] varchar (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Portal] varchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
   [Shopping] varchar (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
   ) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Coption] WITH NOCHECK ADD
   CONSTRAINT [DF_Coption_CompanyID] DEFAULT (0) FOR [CompanyID] ,
   CONSTRAINT [DF_Coption_InitPrice] DEFAULT (0) FOR [InitPrice] ,
   CONSTRAINT [DF_Coption_Price] DEFAULT (0) FOR [Price] ,
   CONSTRAINT [DF_Coption_Price2] DEFAULT (0) FOR [Price2] ,
   CONSTRAINT [DF_Coption_Price3] DEFAULT (0) FOR [Price3] ,
   CONSTRAINT [DF_Coption_Discount] DEFAULT (0) FOR [Discount] ,
   CONSTRAINT [DF_Coption_Retail] DEFAULT (0) FOR [Retail] ,
   CONSTRAINT [DF_Coption_Retail2] DEFAULT (0) FOR [Retail2] ,
   CONSTRAINT [DF_Coption_Retail3] DEFAULT (0) FOR [Retail3] ,
   CONSTRAINT [DF_Coption_BusPrice] DEFAULT (0) FOR [BusPrice] ,
   CONSTRAINT [DF_Coption_BusRetail] DEFAULT (0) FOR [BusRetail] ,
   CONSTRAINT [DF_Coption_BusAccts] DEFAULT (0) FOR [BusAccts] ,
   CONSTRAINT [DF_Coption_BusAcctPrice] DEFAULT (0) FOR [BusAcctPrice] ,
   CONSTRAINT [DF_Coption_BusAcctRetail] DEFAULT (0) FOR [BusAcctRetail] ,
   CONSTRAINT [DF_Coption_IsCatalog] DEFAULT (0) FOR [IsCatalog] ,
   CONSTRAINT [DF_Coption_IsDiscount] DEFAULT (0) FOR [IsDiscount] ,
   CONSTRAINT [DF_Coption_Billing] DEFAULT (0) FOR [Billing] ,
   CONSTRAINT [DF_Coption_CommRate] DEFAULT (0) FOR [CommRate] ,
   CONSTRAINT [DF_Coption_PromoCode] DEFAULT (0) FOR [PromoCode] ,
   CONSTRAINT [DF_Coption_AccessLimit] DEFAULT ('') FOR [AccessLimit] ,
   CONSTRAINT [DF_Coption_QuizLimit] DEFAULT (0) FOR [QuizLimit] ,
   CONSTRAINT [DF_Coption_MemberLimit] DEFAULT (0) FOR [MemberLimit] ,
   CONSTRAINT [DF_Coption_TrialDays] DEFAULT (0) FOR [TrialDays] ,
   CONSTRAINT [DF_Coption_IsTrialPayment] DEFAULT (0) FOR [IsTrialPayment] ,
   CONSTRAINT [DF_Coption_IsSignIn] DEFAULT (0) FOR [IsSignIn] ,
   CONSTRAINT [DF_Coption_IsJoinNow] DEFAULT (0) FOR [IsJoinNow] ,
   CONSTRAINT [DF_Coption_IsNewEmail] DEFAULT (0) FOR [IsNewEmail] ,
   CONSTRAINT [DF_Coption_IsBusAcct] DEFAULT (0) FOR [IsBusAcct] ,
   CONSTRAINT [DF_Coption_IsFree] DEFAULT (0) FOR [IsFree] ,
   CONSTRAINT [DF_Coption_RefName] DEFAULT ('') FOR [RefName] ,
   CONSTRAINT [DF_Coption_NewMemberOrgs] DEFAULT ('') FOR [NewMemberOrgs] ,
   CONSTRAINT [DF_Coption_TBPage] DEFAULT ('') FOR [TBPage] ,
   CONSTRAINT [DF_Coption_Languages] DEFAULT ('') FOR [Languages] ,
   CONSTRAINT [DF_Coption_UploadURL] DEFAULT ('') FOR [UploadURL] ,
   CONSTRAINT [DF_Coption_SetupFee] DEFAULT (0) FOR [SetupFee] ,
   CONSTRAINT [DF_Coption_IsSalesDefault] DEFAULT (0) FOR [IsSalesDefault] ,
   CONSTRAINT [DF_Coption_ProjectsDefault] DEFAULT (0) FOR [ProjectsDefault] ,
   CONSTRAINT [DF_Coption_DocSizeLimit] DEFAULT (0) FOR [DocSizeLimit] ,
   CONSTRAINT [DF_Coption_FreeOptions] DEFAULT ('') FOR [FreeOptions] ,
   CONSTRAINT [DF_Coption_EasyOptions] DEFAULT ('') FOR [EasyOptions] ,
   CONSTRAINT [DF_Coption_Options] DEFAULT ('') FOR [Options] ,
   CONSTRAINT [DF_Coption_Options2] DEFAULT ('') FOR [Options2] ,
   CONSTRAINT [DF_Coption_Options3] DEFAULT ('') FOR [Options3] ,
   CONSTRAINT [DF_Coption_Options4] DEFAULT ('') FOR [Options4] ,
   CONSTRAINT [DF_Coption_Options5] DEFAULT ('') FOR [Options5] ,
   CONSTRAINT [DF_Coption_Options6] DEFAULT ('') FOR [Options6] ,
   CONSTRAINT [DF_Coption_Options7] DEFAULT ('') FOR [Options7] ,
   CONSTRAINT [DF_Coption_Options8] DEFAULT ('') FOR [Options8] ,
   CONSTRAINT [DF_Coption_FreeName] DEFAULT ('') FOR [FreeName] ,
   CONSTRAINT [DF_Coption_PaidName] DEFAULT ('') FOR [PaidName] ,
   CONSTRAINT [DF_Coption_PaidName2] DEFAULT ('') FOR [PaidName2] ,
   CONSTRAINT [DF_Coption_PaidName3] DEFAULT ('') FOR [PaidName3] ,
   CONSTRAINT [DF_Coption_Identify] DEFAULT (0) FOR [Identify] ,
   CONSTRAINT [DF_Coption_Identification] DEFAULT ('') FOR [Identification] ,
   CONSTRAINT [DF_Coption_MerchantCardType] DEFAULT (0) FOR [MerchantCardType] ,
   CONSTRAINT [DF_Coption_MerchantCheckType] DEFAULT (0) FOR [MerchantCheckType] ,
   CONSTRAINT [DF_Coption_MerchantCardAcct] DEFAULT ('') FOR [MerchantCardAcct] ,
   CONSTRAINT [DF_Coption_MerchantCheckAcct] DEFAULT ('') FOR [MerchantCheckAcct] ,
   CONSTRAINT [DF_Coption_WalletType] DEFAULT ('') FOR [WalletType] ,
   CONSTRAINT [DF_Coption_WalletAcct] DEFAULT ('') FOR [WalletAcct] ,
   CONSTRAINT [DF_Coption_PayoutProcessors] DEFAULT ('') FOR [PayoutProcessors] ,
   CONSTRAINT [DF_Coption_PaymentOptions] DEFAULT ('') FOR [PaymentOptions] ,
   CONSTRAINT [DF_Coption_MiscPay1] DEFAULT ('') FOR [MiscPay1] ,
   CONSTRAINT [DF_Coption_MiscPay2] DEFAULT ('') FOR [MiscPay2] ,
   CONSTRAINT [DF_Coption_MiscPay3] DEFAULT ('') FOR [MiscPay3] ,
   CONSTRAINT [DF_Coption_IPLimit] DEFAULT (0) FOR [IPLimit] ,
   CONSTRAINT [DF_Coption_InputOptions] DEFAULT ('') FOR [InputOptions] ,
   CONSTRAINT [DF_Coption_GAAcct] DEFAULT ('') FOR [GAAcct] ,
   CONSTRAINT [DF_Coption_Countries] DEFAULT ('') FOR [Countries] ,
   CONSTRAINT [DF_Coption_MenuColors] DEFAULT ('') FOR [MenuColors] ,
   CONSTRAINT [DF_Coption_Portal] DEFAULT ('') FOR [Portal] ,
   CONSTRAINT [DF_Coption_Shopping] DEFAULT ('') FOR [Shopping]
GO

ALTER TABLE [dbo].[Coption] WITH NOCHECK ADD
   CONSTRAINT [PK_Coption] PRIMARY KEY NONCLUSTERED
   ([CoptionID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO

CREATE INDEX [I_Coption_CompanyID]
   ON [dbo].[Coption]
   ([CompanyID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO