EXEC [dbo].pts_CheckTable 'GCR'
 GO

CREATE TABLE [dbo].[GCR] (
   [GCRID] int IDENTITY (1,1) NOT NULL 
   ) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GCR] WITH NOCHECK ADD

GO

ALTER TABLE [dbo].[GCR] WITH NOCHECK ADD
   CONSTRAINT [PK_GCR] PRIMARY KEY NONCLUSTERED
   ([GCRID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO