EXEC [dbo].pts_CheckTableRebuild 'GCR'
 GO

ALTER TABLE [dbo].[GCR] WITH NOCHECK ADD

GO

ALTER TABLE [dbo].[GCR] WITH NOCHECK ADD
   CONSTRAINT [PK_GCR] PRIMARY KEY NONCLUSTERED
   ([GCRID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO