EXEC [dbo].pts_CheckTable 'GFTG'
 GO

CREATE TABLE [dbo].[GFTG] (
   [GftgID] int IDENTITY (1,1) NOT NULL 
   ) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GFTG] WITH NOCHECK ADD

GO

ALTER TABLE [dbo].[GFTG] WITH NOCHECK ADD
   CONSTRAINT [PK_GFTG] PRIMARY KEY NONCLUSTERED
   ([GftgID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO