EXEC [dbo].pts_CheckTableRebuild 'GFTG'
 GO

ALTER TABLE [dbo].[GFTG] WITH NOCHECK ADD

GO

ALTER TABLE [dbo].[GFTG] WITH NOCHECK ADD
   CONSTRAINT [PK_GFTG] PRIMARY KEY NONCLUSTERED
   ([GftgID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO