EXEC [dbo].pts_CheckTable 'Legacy'
 GO

CREATE TABLE [dbo].[Legacy] (
   [LegacyID] int IDENTITY (1,1) NOT NULL 
   ) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Legacy] WITH NOCHECK ADD

GO

ALTER TABLE [dbo].[Legacy] WITH NOCHECK ADD
   CONSTRAINT [PK_Legacy] PRIMARY KEY NONCLUSTERED
   ([LegacyID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO