EXEC [dbo].pts_CheckTable 'PB'
 GO

CREATE TABLE [dbo].[PB] (
   [PBID] int IDENTITY (1,1) NOT NULL 
   ) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PB] WITH NOCHECK ADD

GO

ALTER TABLE [dbo].[PB] WITH NOCHECK ADD
   CONSTRAINT [PK_PB] PRIMARY KEY NONCLUSTERED
   ([PBID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO