EXEC [dbo].pts_CheckTableRebuild 'PB'
 GO

ALTER TABLE [dbo].[PB] WITH NOCHECK ADD

GO

ALTER TABLE [dbo].[PB] WITH NOCHECK ADD
   CONSTRAINT [PK_PB] PRIMARY KEY NONCLUSTERED
   ([PBID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO