EXEC [dbo].pts_CheckTableRebuild 'R180'
 GO

ALTER TABLE [dbo].[R180] WITH NOCHECK ADD

GO

ALTER TABLE [dbo].[R180] WITH NOCHECK ADD
   CONSTRAINT [PK_R180] PRIMARY KEY NONCLUSTERED
   ([R180ID])
   WITH FILLFACTOR = 80 ON [PRIMARY]
GO